### ISSUE TITLE
scalar bar as separate image, or outside window

### ISSUE THREAD

**Issue by dansand** [pyvista/pyvista#1073]
It would be great to have the capability to either save the scalar bar as a separate figure, or to place the scalar bar outside the window. 

For example, it would be useful to be able to emulate the figure/colorbar arrangements discussed here:

https://stackoverflow.com/questions/13784201/matplotlib-2-subplots-1-colorbar

Thanks

**Comment by avaruuser** [comment]
Has there been any progress on this? I am also looking for a way to have a colorbar across subplots.

**Comment by banesullivan** [comment]
I think this has been implemented via our wrappings of `LookupTable`, see https://docs.pyvista.org/api/plotting/_autosummary/pyvista.lookuptable#pyvista-lookuptable

this lets you plot the scalar bars as their own render window.

```py
import pyvista as pv

pl = pv.Plotter()
actor = pl.add_mesh(pv.Wavelet())
actor.mapper.lookup_table.plot()
```
![screenshot (1)](https://github.com/user-attachments/assets/e8b966a0-0209-4ccd-9f1c-9d32816f98bd)

... though this should probably say the scalar name rather than the name of the colormap.... 👀
