### ISSUE TITLE
Fix Light Classes

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#1172]
Was playing around with lighting + shadows and you can make some really cool plots:

![image](https://user-images.githubusercontent.com/11981631/107855627-ccbd6c00-6de0-11eb-880f-044dc65a9d12.png)

Code:
```py
pl = pv.Plotter(lighting=None)
pl.background_color = 'w'
light = pv.Light(position=(10, 10, -10), light_type='scene light')
pl.add_light(light)
pl.add_mesh(surf, color='w', show_edges=False, smooth_shading=True)
pl.renderer.UseShadowsOn()
pl.camera_position = 'yx'
pl.show()
```

However, when playing around with the lighting I had a few issues.  First, when setting the lighting from `pv.Plotter`, setting an invalid lighting style results in a non-descriptive error:
```py
>>> pv.Plotter(lighting='invalid')
ValueError: Invalid lighting option "invalid".
```

It would be better to raise an error with the available lighting.

Additionally, we should subclass our lights.  And not set the light type from a string, especially if certain light types don't have properties.  For example:
```py

plotter = pv.Plotter(lighting='none')
plotter.add_mesh(mesh, color='tan', smooth_shading=True)
light = pv.Light(light_type='headlight')
# these don't do anything for a headlight:
light.position = (1, 2, 3)
light.focal_point = (4, 5, 6)
plotter.add_light(light)
plotter.show()
```

We should just have a `Headlight` class:
```py

class Headlight(Light):
    #...
    # omit position and focal_point properties
```

Note, the base `Light` class cannot have the position and focal_point attributes since those would be inherited by `HeadLight`.  Instead, either add those attributes to the other classes, or just make another class that has those attributes.

Additionally, for module organization, lets not import `Lights` at the main module leve, but have them at the sub-module `light` module level.  That way we can just go and see a list of available lights with any IDE worth its salt.
```
pv.lights.<press tab>
```

**Comment by akaszynski** [comment]
Pinging @adeak.  Apparently I can't "assign" you an issue unless you're part of the dev team.  Want to join the club?

**Comment by adeak** [comment]
> Pinging @adeak. Apparently I can't "assign" you an issue unless you're part of the dev team. Want to join the club?

Thanks, yeah, let's go for it. The time and bandwidth I have for pyvista fluctuates a lot, but I do feel responsible for the lights :)

> Was playing around with lighting + shadows [...]

I tried shadowing in a simple situation (sphere shadowing a box) and the result looked pretty terrible. It might have had to do with the resolution of the meshes or something else, but anyway I concluded that I'm just not going to go there with the PR. I'm very glad to see it work after all!

> First, when setting the lighting from pv.Plotter, setting an invalid lighting style results in a non-descriptive error:

Personally, I'm happy with that error: an invalid value was passed, and one can look at the docs to see what _are_ valid values. I don't mind adding the valid options either, but then there's the burden of updating the error message if new lighting systems are ever added (not a _huge_ burden, just something to consider).

> Additionally, we should subclass our lights.

That's an interesting idea. It would definitely help with the "this kind of light doesn't have this feature" problem you mentioned, although there are similar feature restrictions that do not only depend on the light's type (i.e. directional vs. positional vs. spotlight).

The only issue I can think of is that subclassing would make turning one type of light into another impossible. But this is probably not a huge issue in practice, and the benefits of using subclasses are probably worth it.

 > lets not import Lights at the main module leve, but have them at the sub-module light module level
 
 That could work. I'm wondering if we should then keep pulling in the `LightType` enum values into the `Light` class. I could imagine them being module-level globals instead, as in `pv.lights.HEADLIGHT`.
 
---

Since we're here, I found two issues myself when I implemented `Light`, but one or both might stem from VTK itself.
  
Firtly, lighting systems interact across the subplots of a `Plotter`. I couldn't find our why, there might be something implicit under the hood (in the pipeline) that gets shared between renderers. Here's an example using bare vtk lights:
```py
import vtk
import pyvista as pv
plotter = pv.Plotter(shape='1|1')
for i in range(2):
    plotter.subplot(i)
    plotter.show_axes()
    plotter.renderer.RemoveAllLights()
    plotter.renderer.AddLight(vtk.vtkLight())
    plotter.add_mesh(pv.Cube())
for light in plotter.renderers[-1].GetLights():
    light.SetIntensity(light.GetIntensity()/2)
plotter.show()
```
The two subplots have quite clearly have independent lights added to them. However if you rotate the cube in one subplot the light start to rotate in the other subplot. And this is with a default `vtkLight` type, which should be a scene light! I have no idea what's causing this.

Secondly, and this is almost certainly a VTK bug, but camera lights have actors that are stuck in a single position as if they were scene lights, making the actor useless:
```py
import pyvista as pv

plotter = pv.Plotter(lighting='none')
plotter.add_mesh(pv.Cube())
light = pv.Light(light_type='camera light')
light.position = (1, 2, 3)
light.positional = True
light.cone_angle = 20
light.show_actor()
plotter.add_light(light)

plotter.show()
```
If you rotate the scene around you can see that the lighting varies (as it should, since the light is attached to the camera), but the actor is stationary with respect to the cube. For instance rolling the scene by 180 degrees around the camera makes the actor point at a dark face of the cube.

**Comment by akaszynski** [comment]
Invite sent.  No pressure for working on this project.  I'm often stretched as it is, but it's a "fun" thing to work on when I have time to.  Sometimes I work on it because it lines up with work or some other closed source projects.

As for the shadows, it works 100% of the time 60% of the time.  We should add as an option and then users can play around with it.  I'm sure at some point real time ray tracing is going to be a hardware feature even down to integrated GPUs, so it's a matter of time until this becomes a well tested/supported feature.

> That could work. I'm wondering if we should then keep pulling in the LightType enum values into the Light class. I could imagine them being module-level globals instead, as in pv.lights.HEADLIGHT.

Yes, a `lights` module level.  We can move lights into its own module within `plotting` I think, or have it as a top level module.  As this project grows, isolation will be important.

> Personally, I'm happy with that error: an invalid value was passed, and one can look at the docs to see what are valid values. I don't mind adding the valid options either, but then there's the burden of updating the error message if new lighting systems are ever added (not a huge burden, just something to consider).

If you reuse a list when printing out the error, there no duplication.  For example:

```py
>>> allowed = [1, 2, 3]
>>> user_input = 0
>>> if user_input not in allowed:
>>>     raise ValueError(f'Invalid input: {user_input}\nAllowed values: {allowed}')
ValueError: Invalid input: 0
Allowed values: [1, 2, 3]

```

> The only issue I can think of is that subclassing would make turning one type of light into another impossible. But this is probably not a huge issue in practice, and the benefits of using subclasses are probably worth it.

I think it's more intuitive just to change the class when the light is created, and to me this makes more sense.  This isn't up to me though, and we can still go with your approach.

**Comment by adeak** [comment]
> As for the shadows, it works 100% of the time 60% of the time. 
I just tried your example with `surf = pv.examples.download_motor()`, and it looks terrible. It might have to do with the dumb integrated GPU in my laptop.

But the same example revealed another bug: the `vtkLightActor` complains that the light is not a spotlight. I mean that's not wrong, but the actor shouldn't get rendered. If I remove the `UseShadowsOn()` call this goes away...

> If you reuse a list when printing out the error, there no duplication.

Yeah, we could do that. I was thinking along the "error handling in the `else` branch" scenario, but I guess there's no reason why we can't check the options ahead of time and drop the `else`.

> I think it's more intuitive just to change the class when the light is created, and to me this makes more sense. This isn't up to me though, and we can still go with your approach.

No, I think subclasses will be fine. We'll just have to make sure the available light type subclasses in the `lights` namespace are as discoverable as available values for the `light_type` keyword are in the current implementation (which is naturally well localized).

**Comment by akaszynski** [comment]
Works quite well with NVIDIA
```
        GPU Vendor : NVIDIA Corporation
      GPU Renderer : Quadro M620/PCIe/SSE2
       GPU Version : 4.5.0 NVIDIA 390.141
```

```py
import pyvista as pv
from pyvista import examples
surf = examples.download_motor()

pl = pv.Plotter(lighting=None)
pl.background_color = 'w'
light = pv.Light(position=(10, 10, -10), light_type='scene light')
pl.add_light(light)
pl.add_mesh(surf, color='w', show_edges=False, smooth_shading=True)
pl.renderer.UseShadowsOn()
pl.show()
```
![image](https://user-images.githubusercontent.com/11981631/107862145-e8883880-6e07-11eb-8fc8-10923b02968f.png)

It's funny how it complains about the light not being a spotlight, because the shadows look great regardless.

**Comment by adeak** [comment]
Can't say I'm not envious a bit ;)

> It's funny how it complains about the light not being a spotlight, because the shadows look great regardless.

It's only the light actor attached to every light that's complaining. You can have perfect shadows with a directional light.

In the implementation every `Light` automatically gets a light actor, but these stay hidden unless the light is a spotlight. This normally stops the light actor from screaming that its light is not a spotlight. For some reason, however, the light actor tries to be rendered when shadowing is enabled.

The reason I went with this design is because otherwise we must create light actors on demand (only when the light is a spotlight), which we then have to register with the renderer of the plotters that the light has been added to... Not a very local thing and I'd avoid it if possible. Still, a nonsense error with shadowing is not great either.

**Comment by adeak** [comment]
Replying to myself so that I don't forget this:

> That could work. I'm wondering if we should then keep pulling in the LightType enum values into the Light class. I could imagine them being module-level globals instead, as in pv.lights.HEADLIGHT.

The problem with this would be that we'd have `pv.lights.Headlight` as a light subclass, and `pv.lights.HEADLIGHT` as one of the values of the `pv.lights.LightType` enum (which is an int subclass).

_But_ if we switch to using subclasses for the light types we probably don't need the `LightType` enum to begin with! The type of the light would be obvious. So this would be a non-issue after all.

**Comment by akaszynski** [comment]
Many of the issues raised here (like the spotlight actor issue) were solved in #1247.  @adeak, feel free to reopen this, but I think the current implementation is sufficient.

**Comment by adeak** [comment]
Thanks for the heads-up @akaszynski. I wasn't going to have time to work on this for a few weeks still. When I do I'll see if there's anything we should still do that was raised here.

**Comment by sunitasaha** [comment]
Hello. I am using pyvista to render a scene. where I have added a **headlight** and **set camera position**. Now I am **rotating** the mesh slowly and taking a screenshot everytime. In some of my images I see dark patches and its **quite randomly occurs**. I dont have any duplicate faces. My mesh is perfectly convex. I dont understand the root cause of this. Could you provide me some suggestions to try? Offscreen is true. Here are some images. 
![image](https://github.com/pyvista/pyvista/assets/70508935/75bf337a-41bf-4f2a-850f-1302383cad1f)
![image](https://github.com/pyvista/pyvista/assets/70508935/6d99559c-67cf-40d6-8b67-45c76179e79b)
![image](https://github.com/pyvista/pyvista/assets/70508935/e21ec77b-2919-4e25-b3e9-ec7be8ae5495)
![image](https://github.com/pyvista/pyvista/assets/70508935/1298943d-faa4-404e-9e55-ecb5bc90f6be)
