### ISSUE TITLE
Very minor irritation: filters with `inplace=True` should return self

### ISSUE THREAD

**Issue by darikg** [pyvista/pyvista#1296]
There's a common pattern in `pyvista.core.filters` along the lines of `if inplace: return None`. My intutition is that all filters should return a mesh, whether it's a newly created one or `self` modified in place. Happy to submit a PR to change this behavior, but maybe there's a good reason for it I'm unaware of?

**Comment by akaszynski** [comment]
> My intutition is that all filters should return a mesh, whether it's a newly created one or self modified in place.

That's actually not a bad idea.  There's zero cost to returning another reference to `self`, and it deals with inconsistent outputs.  Probably at one point when this was implemented it seemed like a good idea to return `None`.  Looking at this afresh, I think that methods should always have a consistent return, even if it's the same mesh.

> Happy to submit a PR to change this behavior, but maybe there's a good reason for it I'm unaware of?

0.30 keeps getting delayed, so if you can do this soon (i.e. today/tomorrow) I'd be happy to review and merge.  Feel free to start something, push, and let me know when I can start hacking it.  I agree that it's an annoying inconsistency to our API.

**Comment by larsoner** [comment]
> Probably at one point when this was implemented it seemed like a good idea to return None.

At one point I think it was semi-standard practice to return None for inplace operations, e.g. 

https://docs.python.org/3/faq/design.html#why-doesn-t-list-sort-return-the-sorted-list

FWIW in MNE-Python years ago we made the decision that the convenience of chaining operations that work in-place was worth it (e.g. you can do `data = a.filter(...).decimate(...).get_data()`). I am glad we made this decision and stuck to it as it's an idiom people ended up using a lot, and we don't really get complaints about ambiguity of inplace/copy. So +1 from me to always return here as well

**Comment by adeak** [comment]
It's still very much good form not to return anything for mutating operations. This is one of the few things that the builtins do consistently. I can think of `dict.setdefault` as an exception but there probably aren't many (any?) other examples.

The fluent API style that would be enabled by returning even when `inplace=True` is generally not considered pythonic. And I'm not sure I see the use case that is enabled by being able to chain _in-place_ operations. Is the fluent example in @larsoner's post not the same as
```
a = a.filter(...).decimate(...)
data = a.get_data()
```
with non-in-place filters? It doesn't seem too terrible to me.

None of this is necessarily an issue about this approach, just my two cents.

**Comment by darikg** [comment]
I guess I could see an issue with methods that either do or don't operate inplace, and having to remember which is which (like the `list.sort` and `list.sorted` example), but in pyvista where nothing defaults to inplace and inplace operations only ever occur with an explicit `inplace=True` argument, I just don't see the confusion argument.  The advantage to me is when you're writing a convenience method that dispatches to a chain of other filters, you don't need to handle inplace or not, just chain your calls and forward the inplace argument.

That said, it's extremely subjective so whatever the popular consensus is is probably best.

**Comment by adeak** [comment]
Good point about this being two modes of operation for the same method. This also ties in with @akaszynski's type consistency remark.

After some introspection I've traced my opinion back to two things (beyond past discussions with opinionated python devs): 1. numpy ufuncs which have an `out` kwarg and I _thought_ don't return it (but they do!), and 2. pandas where `inplace` is everywhere and doesn't return the result, see also [this Q&A](https://stackoverflow.com/questions/43893457/understanding-inplace-true) for some opinions.

**Comment by darikg** [comment]
I don't use `out` in numpy often enough to have an opinion there. The pandas comparison is interesting though. I admit I chuckled a bit over how the second bulletpoint for "pandas inplace=True considered harmful" is that "inplace does not work with method chaining"--that's my whole point! Anyway--the two other main arguments there are 1) there's probably very little performance benefit because you're not really avoiding any copies and 2) can lead to `SettingWithCopyWarning`.

(1) is totally fair and I think is (having done zero profiling) probably also the case with pyvista. The distinction between inplace or not seems to be entirely on the python side, not in VTK. 

(2) I'm on the fence on. I find the difference here is that it's rare for me to write broadly useful methods that chain together a bunch of pandas operations, so I tend to use `inplace` there in a much more bespoke manner, whereas with pyvista a lot of the operations I do are more repetitive and mundane, e.g. a `clean`, `triangulate`, `compute_normals`, etc. That said, I don't recall I've ever had a problem with `SettingWithCopyWarning`, though I totally understand wanting to avoid confusing aliasing-related bugs.

**Comment by adeak** [comment]
All things considered "make function return types consistent" and "don't return result from mutating methods" are both reasons for purity, and we have to choose one. Personally for me the latter is still more important (it's not that terrible to return different types when you ask for it using input arguments, see also the `return_*` arguments that force outputs to be tuples of meshes rather than meshes). But I can't say that either is fundamentally better than the other.

So you have my "meh" :smile:

**Comment by adeak** [comment]
> 0.30 has been delayed enough as it is. Let's press for next release for this. @darikg feel free to open up a PR, otherwise one of us will (but it might take longer).

They already have https://github.com/pyvista/pyvista/pull/1299 :)

**Comment by akaszynski** [comment]
Ok.  It will be out in the next release.  Two to close and then we're good.

**Comment by darikg** [comment]
> Reading this (and learning that chaining operators is called a "Fluent API"), it's clear that both approaches can work. Considering how verbose `inplace` is with chained operators, I doubt that anyone is going to do:
> 
> ```
> mesh.triangulate(inplace=True).<some_filter>(inplace=True)
> ```

My original post stemmed from wanting to do something like:

```python
def my_convenience_fn(mesh, inplace=False):
    return (
        mesh
        .clean(inplace=inplace)
        .triangulate(inplace=inplace)
        .compute_normals(inplace=inplace)
    )
```

> ### Scheduling
> 0.30 has been delayed enough as it is. Let's press for next release for this. @darikg feel free to open up a PR, otherwise one of us will (but it might take longer).

Sorry, I don't quite understand what's required beyond #1299. Also, could someone help me understand why CI is only failing on Linux?)

**Comment by banesullivan** [comment]
Reopening this for discussion because of #1861 and #1855. I am highly opposed to this change and would like to revert it.

**Comment by banesullivan** [comment]
I have to apologize a bit, I reopened this without reading through the entire discussion. I'll admit you all did a thorough evaluation of this and have also gotten me on the "meh" side of implementing this change. Fundamentally though, I am opposed to this.

It is my opinion that any mutating method should never return anything:

1. For consistency with Python builtins
2. To signify that there is no "output" of the operating "filter" per the convention I worked hard to implement with the filters
3. To prevent any confusion with the fact that there are several filters that actually operate inplace by default

@darikg 
> I guess I could see an issue with methods that either do or don't operate inplace, and having to remember which is which (like the list.sort and list.sorted example), but in pyvista where nothing defaults to inplace and inplace operations only ever occur with an explicit inplace=True argument, I just don't see the confusion argument.

This was an assumption that has proven to fail in #1860 and in the example I gave in https://github.com/pyvista/pyvista/issues/1855#issuecomment-979774232

```py
>>> import pyvista as pv
>>> box = pv.Box()
>>> left = box.remove_cells([0,1,2])
>>> right = box.remove_cells([3,4,5])
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
/var/folders/2x/4df66vz13pv4hj_ysv23tyyc0000gn/T/ipykernel_85626/2585597499.py in <module>
      2 
      3 left = box.remove_cells([0,1,2])
----> 4 right = box.remove_cells([3,4,5])

~/Software/pyvista/pyvista/pyvista/core/pointset.py in remove_cells(self, ind, inplace)
    110                                  f'number of cells ({self.n_cells}')
    111         ghost_cells = np.zeros(self.n_cells, np.uint8)
--> 112         ghost_cells[ind] = _vtk.vtkDataSetAttributes.DUPLICATECELL
    113 
    114         if inplace:

IndexError: index 3 is out of bounds for axis 0 with size 3
```


Generally I can get on board with these return values, if and only if the *all* inplace operations in PyVista are indeed opt-in which I am working towards in #1860. However there are a few methods that have defaulted to inplace since before I implemented the general filters classes, e.g. the `rotate_*` filters on `PolyData`. Because of these inconsistencies I am opposed to this change.

I see two routes forward:

1. Revert this change
2. Fix any inconsistencies and make sure inplace operations are always an opt-in feature

I will push for route 2 here as 1 seems counterproductive to me at this point. However, route 2 may break some downstream code and for that reason, I'd be willing to let the legacy `rotate_*` methods and a potentially a few other *`PolyData`-specific filters* be an exception to this rule. However, I would like to track down all of these and document them as legacy methods that have a preferred new method with `default=False` as the default.

**Comment by adeak** [comment]
The way to make some of those breaking changes in an end-user friendly (but potentially not downstream-library friendly) way is to switch from default `inplace=True` to `inplace=None`, raise a `Warning` (`FutureWarning`?) for the `None` case that behaviour will change in `x` releases/time, and setting `inplace=True` until that number of releases/time passes.

This would let end users realise that their code will change, and adapt to it by being explicit with their `inplace` parameters. Library authors would potentially be more inconvenienced because this would lead to warnings in CI, and they might not be able to choose a specific `inplace` value. And there's always a chance that an end user updates every total solar eclipse, missing out on warning entirely (especially with PyVista's normally frequent release schedule).

**Comment by banesullivan** [comment]
Closing this as #1860 addressed concerns and this is now a part of the API
