### ISSUE TITLE
`DataSet.vectors` does not work with cell data

### ISSUE THREAD

**Issue by MatthewFlamm** [pyvista/pyvista#1430]
**Describe the bug, what's wrong, and what you expect:**

`DataSet.vectors` does not work with cell data as it adds to `DataSet.point_arrays`.  

This is easily fixed, but I would be in favor of totally deprecating this functionality as it duplicates the `DataSet["my_vector_name"] = data` functionality.  It is confusing to me why there is a special method here.  It was also confusing in https://github.com/pyvista/pyvista-support/issues/448 and partially in https://github.com/pyvista/pyvista-support/issues/438.

-----

**To Reproduce**

Please include a code snippet to reproduce the bug in the block below:

```py
mesh = pv.Plane()
mesh.vectors = np.ones([mesh.n_cells, 3])
```

**Comment by mountaindust** [comment]
In reference to pyvista/pyvista-support#448, `DataSet.vectors` should naturally be expected to set VECTOR data but instead sets SCALAR data as a multi-component scalar.  As @MatthewFlamm points out in pyvista/pyvista-support#448, plotting then seems to treat that SCALAR data as if it were VECTOR data, which is another bug according to the VTK specification. 

To reproduce, one can run the sphere example and output to an ascii vtk file to see the difference:
```python
sphere = pv.Sphere(radius=3.14)
vectors = np.vstack(
    (
        np.sin(sphere.points[:, 0]),
        np.cos(sphere.points[:, 1]),
        np.cos(sphere.points[:, 2]),
    )
).T
sphere.vectors = vectors * 0.3
sphere.save('sphere.vtk', binary=False)
```
If you open the resulting file in a text editor and scroll down to the POINT_DATA field, you get:

    POINT_DATA 842
    SCALARS _vectors float 3
    LOOKUP_TABLE default

rather than the expected

    POINT_DATA 842
    VECTORS vectors float

Additionally, plotting this data set with
```python
sphere.arrows.plot(scalars='GlyphScale')
```
results in a plot that transforms during rotation like VECTOR data should, and like SCALAR data shouldn't.

Finally, I can currently find no way to set VECTOR data in pyvista without resorting to the underlying VTK API. My work-around at the moment for anybody who might be trying to do this is as follows:
```python
from vtk.util import numpy_support
vectors_vtk = numpy_support.numpy_to_vtk(vectors)
vectors_vtk.SetName('myvectors') # name for the dataset, to replace the default 'vectors'
sphere_pt_data = sphere.GetPointData()
sphere_pt_data.SetVectors(vectors_vtk)
sphere.save('sphere.vtk', binary=False)
```

**Comment by MatthewFlamm** [comment]
I think you meant https://github.com/pyvista/pyvista/issues/1431 ?  I think this information is best continued there, can you post it there is well?  I see these issues as separate but very related.  This one is related to the broken cell data addition to vectors and the fact that it is a duplication of other more consistent interfaces.  If the VECTORS attribute is added later, then it may make sense to have a special method for this again, but it may not.

**Comment by mountaindust** [comment]
Yes! Thank you. I did mean #1431, and I agree that the information is best continued there (I didn't realize at the time it had been transferred). I will edit my comment with the correct issue number, and try to clean things up a bit. I'll also post my current work around in #1431.

**Comment by akaszynski** [comment]
> I can currently find no way to set VECTOR data in pyvista

We need a way of exposing VTK's `SetVectors` within our APIs and need to open a specific issue for that.

> I would be in favor of totally deprecating this functionality as it duplicates the `DataSet["my_vector_name"] = data` functionality

Agreed, and we could probably accomplish that with one ~~stone~~ PR.

**Comment by MatthewFlamm** [comment]
> We need a way of exposing VTK's `SetVectors` within our APIs and need to open a specific issue for that.

I think #1431 should suffice for that.  Lets continue moving that piece of the conversation there.
