### ISSUE TITLE
More render window keyboard shortcuts

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#149]
We should add more render window shortcuts - and we need to make sure they work with the Qt background plotter (they currently don't)

- Use numerical keys (0, 1, 2, 3, ..., 9 ) to save and reload camera locations
- p/P to adjust the point size of actors in the scene
- l/L to adjust line width of actors in the scene
- command + s: to save a screenshot - pop up a save dialog
- some sort of button to activate cell picking mode (relevant to #278)

Any other suggestions?

**Comment by akaszynski** [comment]
As configured, "s" changes the representation to surface, and "w" changes it to wireframe.  "p" should change the representation to points.  Maybe we can use "+" and "-" to change the size of the wireframe and point size, depending on the active representation style.  Your approach also works.

I'd also like to see "ctrl+s" to be used for saving screenshots, but we would have to add a dependency to a GUI toolkit like ``PyQt``.  Since it's already required for the ``BackgroundPlotter`` maybe we can raise an exception or a warning if it's not installed and the user tries to trigger it.

**Comment by prisae** [comment]
Something else to take into consideration. If used within a notebook using panel, it interferes with the jupyter shortcuts. E.g.: I can change to a wireframe plot with `w`, but not back to a surface plot with `s`, because `s` in a notebook saves the notebook...

Maybe this is an issue for panel though?

**Comment by banesullivan** [comment]
Ah yes that's out of our control with PyVista and a `panel` issue... actually the latest release of `panel` turned those keyboard shortcuts off because of https://github.com/pyviz/panel/issues/378

Honestly, I think we will move forward with #268 then try to implement a solution for #258 and favor a more robust toolset like K3D for notebook rendering since the VTKjs API is quite young and VTKjs renderers are difficult to customize. VTKjs is incredibly limited and I think we should seek out a better tool for notebook rendering unfortunately
