### ISSUE TITLE
Active scalars are added and changed if scalar bar title is passed to add_mesh

### ISSUE THREAD

**Issue by p-j-smith** [pyvista/pyvista#1900]
**Describe the bug, what's wrong, and what you expect:**

If I add a mesh and that has active (point data) scalars set, and also set a title for the colour bar, then a new array is added to `mesh.point_data` and has the name of the title. This new array added to `point_data` is also set as the active scalars.

**To Reproduce**
```py
import pyvista as pv

sphere = pv.Sphere()
sphere.point_data['My Data'] = np.arange(sphere.n_points)

plotter = pv.Plotter()
plotter.add_mesh(sphere, scalar_bar_args={"title": "My title"})

print(sphere.point_data)

```

Output:
```
pyvista DataSetAttributes
Association     : POINT
Active Scalars  : My title
Active Vectors  : None
Active Texture  : None
Active Normals  : Normals
Contains arrays :
    Normals                 float32  (842, 3)             NORMALS
    My Data                 int64    (842,)
    My title                int64    (842,)               SCALARS
```
-----

**System Information:**
```txt
  Date: Tue Nov 30 16:34:00 2021 GMT

                OS : Darwin
            CPU(s) : 20
           Machine : x86_64
      Architecture : 64bit
       Environment : Jupyter
        GPU Vendor : ATI Technologies Inc.
      GPU Renderer : AMD Radeon Pro 5700 XT OpenGL Engine
       GPU Version : 4.1 ATI-4.6.20

  Python 3.8.10 | packaged by conda-forge | (default, May 10 2021, 22:58:09)
  [Clang 11.1.0 ]

           pyvista : 0.32.0
               vtk : 9.0.3
             numpy : 1.21.2
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
            meshio : 4.4.6
        matplotlib : 3.4.3
         pyvistaqt : 0.6.dev0
             PyQt5 : 5.15.4
           IPython : 7.26.0
             scipy : 1.7.1
              tqdm : 4.62.2
```

**Comment by MatthewFlamm** [comment]
I have tried to wrestle with this behavior in the past.  I think it happens here: https://github.com/pyvista/pyvista/blob/434f8eecdf0db9a49f067458ab585bc76aab692c/pyvista/plotting/plotting.py#L2135-L2144

The reason is not clear to me.  If the only reason is to add exogenous data passed in `scalars`, i.e. `plotter.add_mesh(mesh, scalars=some_ndarray_of_data)`, to the mesh then this should be handled as a special case so as to not modify existing scalars.  I would not be surprised if this behavior is also tightly coupled with the other plotting backends, which would make modifying this tricky.

**Comment by p-j-smith** [comment]
Thanks for the explanation! I'd be happy to help try to fix it if you have any ideas how to approach it
