### ISSUE TITLE
Help in example for compute_vector

### ISSUE THREAD

**Issue by ammaryasirnaich** [pyvista/pyvista#1978]
Hi, 
    I was looking into one of the examples related to [pointcloud](https://docs.pyvista.org/examples/00-load/create-point-cloud.html#sphx-glr-examples-00-load-create-point-cloud-py) and got a little confused with the **computer_vector** method

```
def compute_vectors(mesh):
    origin = mesh.center
    vectors = mesh.points - origin
    vectors = vectors / np.linalg.norm(vectors, axis=1)[:, None]
    return vectors
```
It will be much appreciated if anyone can elaborate the reason for using  `np.linalg.norm` here?  is it related to calculating the normal vector? 
Thanks

**Comment by MatthewFlamm** [comment]
> It will be much appreciated if anyone can elaborate the reason for using `np.linalg.norm` here? is it related to calculating the normal vector?

`np.linalg.norm` is a numpy function that returns a norm of a vector or matrix.  In this case, it is giving the 2 norm of the vector defined by each point relative to the mesh center (`origin` in the example).  

`vectors = vectors / np.linalg.norm(vectors, axis=1)[:, None]` creates a unit vector.  This is not a normal vector since these are just individual points.

**Comment by ammaryasirnaich** [comment]
@MatthewFlamm Thanks a lot. It really makes sense now. I think the method name should be `compute_unit_vector` as it returns the unit vector.

**Comment by MatthewFlamm** [comment]
> I think the method name should be `compute_unit_vector` as it returns the unit vector.

I _think_ the name might indicate that this is a vector quantity that will be set on the mesh, but I think your suggestion is good too.  Feel free to clarify the example: 

https://github.com/pyvista/pyvista/blob/main/examples/00-load/create-point-cloud.py
