### ISSUE TITLE
Package not available from channel for docs building

### ISSUE THREAD

**Issue by nicoguaro** [pyvista/pyvista#219]
I tried to install the requirements for docs using conda with:

```console
conda install --file requirements_docs.txt --channel conda-forge
```

and obtained the following error:

```console
PackagesNotFoundError: The following packages are not available from current channels:

  - sphinxcontrib-napoleon
  - //github.com/rtfd/sphinx-notfound-page@master
  - pytest-sphinx
  - sphinx-rtd-theme
```

**Comment by banesullivan** [comment]
Ah from https://github.com/openjournals/joss-reviews/issues/1450#issuecomment-493243818, I thought you were running into an issue installing a deployed version of PyVista from the conda-forge channel.

Like many Python projects, not all of our dependencies are available on Anaconda and the majority of our users harness PyPI/`pip` as their package manager. If you are using Conda virtual environments, this shouldn't be an issue as you can ensure `pip` installs these dependencies correctly from PyPI by using `python -m pip install -r requirements_docs.txt` when your virtual env is activated.

The [CONTRIBUTING.md](https://github.com/pyvista/pyvista/blob/master/CONTRIBUTING.md) file outlines how to install the needed requirements to build PyVista's documentation and run tests - since not all of those requirements are available on Anaconda, this is something we will not fix.

@leouieda, thoughts?

**Comment by nicoguaro** [comment]
I am aware that you can install from different sources, and that's what I did. I created this issue per your suggestion.

Nevertheless, mixing conda and pip is still not recommended, in general.

**Comment by banesullivan** [comment]
> Nevertheless, mixing conda and pip is still not recommended, in general.

That's absolutely right - it has the potential to result in unstable virtual environments.

Unfortunately, this isn't something that I think we can address in PyVista. I'm going to close this issue and perhaps chime in at a later date with some resources on using Conda to build and manage dependencies that are only hosted on PyPI

**Comment by leouieda** [comment]
@banesullivan I would suggest creating conda-forge packages for these dependencies. You don't have to be a project author to submit a package to conda-forge. It's best if you ping the authors in the `staged-recipes` PR or in their own repo to ask if anyone else can be a maintainer. Specially for these pure Python packages, it's probably not a lot of work on your part. The conda-forge bots handle making PRs for new releases so it's low maintenance as well.
