### ISSUE TITLE
Distance along poly line/Spline

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#252]
Could we add a way to compute the distance along every node/point in a poly line when creating them via `pyvista.Spline`? pinging @akaszynski 

Note that I added this for straight lines from `pyvista.Line` in #250:

https://github.com/pyvista/pyvista/blob/40172866a491ebc4f643309fbdc75c6e955b693f/pyvista/geometric_objects.py#L262-L267

However this only works for computing distances along straight lines. How would we go about computing the distances of points along a ploy line? And once we figure this out, let's add a `'Distance'` array to the `pyvista.Spline` output by default.

**Comment by banesullivan** [comment]
Perhaps we could just use the [`vtkImplicitPolyDataDistance` class](https://vtk.org/doc/nightly/html/classvtkImplicitPolyDataDistance.html#details)?...

**Comment by akaszynski** [comment]
``vtkImplicitPolyDataDistance`` might not work on coarse splines as it computes the distance to the nearest point, which might not be the "next" point on a line.  From what I've seen online for VTK, there's nothing that computes the distance along the spline.  One workaround would be to generate a very dense interpolation and then compute the distance along that line:

```python
spline = pv.Spline(points, 1000)

dense_spline = pv.Spline(points, 10000)
inc_dist = (np.diff(dense_spline.points, axis=0)**2).sum(1)
dist = np.cumsum(inc_dist)

spline['distance'] = dist[::10]

# tube = spline.tube(radius=0.1)
tube = spline.tube(radius=0.1)
tube.plot(scalars='distance', smooth_shading=True)
```

**Comment by banesullivan** [comment]
I just found out the poly lines/splines are actually linearly segmented. Which means any distance computed along the line would be a sum of Euclidean distances between points along the line.

This is pretty easy to implement so I'll just do a cumulative summation of the distances between the nodes

**Comment by banesullivan** [comment]
Actually, the filter  `vtkAppendArcLength` is meant for exactly this task which I implemented under `PolyData.compute_arc_length`

**Comment by AlexanderJuestel** [comment]
@banesullivan maybe just an addition to this issue: Is there a way to retrieve the XYZ position of a point along this line given a distance? The point is most like not located on a vertex/note but rather located along a linear segment. 

I am particularly interested in that since we can display wells/boreholes including their deviation in PyVista (see image). We then know the stratigraphic boundaries in a given measured depth (along the spline) and would like to get the TVD (true vertical depth) of the point for subsequent structural modeling for instance in GemPy. So that you can combine the representations of the GemPy/Pyvista meshes with the boreholes. 

I am also happy to open a new issue or discussion on that :) 

![image](https://user-images.githubusercontent.com/45469915/182117209-fafca3ed-4bc5-4759-87e3-f0b1bba8c43d.png)
