### ISSUE TITLE
Feature Request: Write Objects in Legacy Format

### ISSUE THREAD

**Issue by supersubscript** [pyvista/pyvista#254]
I've experienced a recent issue in writing polydata files using Vista, and subsequently trying to open them using an earlier version of ParaView. 

Accordingly it would be nice to have the option of saving files in legacy format (".vtk") of certain versions, potentially using a flag like:
```python
mesh.save('file_name.vtk', version='legacy_3.0')
```
or similar.

**Comment by banesullivan** [comment]
Is there a way to do this using VTK? For example, this is basically how we write `.vtk` files at the moment:

```py
import pyvista as pv
from pyvista import examples
import vtk

mesh = examples.load_globe()

writer = vtk.vtkPolyDataWriter()
writer.SetFileName('my_legacy_file.vtk')
writer.SetInputData(mesh)

# TODO: set the legacy version

writer.Write()
```

I'm not aware of a way to do this using VTK...

**Comment by supersubscript** [comment]
As far as I've been able to find, there doesn't seem to be a straightforward way of doing it in VTK... 

[pyvtk](https://github.com/pearu/pyvtk) appears to have some of that functionality.

**Comment by banesullivan** [comment]
Unfortunately, I don't think this is feasible for PyVista as we'd have to maintain a lot of custom file writers for the legacy formats... this is a bit out of scope for PyVista, but perhaps `pyvtk` would be the right place (though that project looks stale). If there is a straightforward API call to save legacy versions using `pyvtk`, I'd be happy to help implement routine to use `pyvtk` for writing in these older formats.

I'd like to encourage users of PyVista to use the latest versions of VTK and ParaView since VTK has seen some awesome development lately which we try to leverage in PyVista. Also, building or acquiring prebuilt binaries for both VTK and ParaView has become a straightforward process lately, so I don't see a compelling reason to add support for writing out to legacy formats.

*Curious, why exactly are you using an older versions of ParaView and what version? I'm guessing you are using an older version of ParaView hosted on some viz nodes of a cluster which is difficult to rebuild/update?*

**Comment by supersubscript** [comment]
Perhaps you're right! It's an issue I stumbled upon, so I thought it'd be worth listing it... :-) I'll have a look at pyvtk at my first opportunity (just getting back from holidays), so I'll update on that if I find anything. 

I agree that it'd be a pretty great world if everyone was up to date with everything, but in my experience things tend to move quite slowly, especially in academia. The reason we're using outdated versions in my lab is simply because our OS's are limited to Ubuntu 16.04LTS, which doesn't carry the latest VTK straightforwardly through vanilla apt. Then there is the good old problem of in-house legacy code, that depends on certain older versions of various toolkits, and such. 

Closing the issue for now.

**Comment by banesullivan** [comment]
> I'll have a look at pyvtk at my first opportunity (just getting back from holidays), so I'll update on that if I find anything.

Awesome, it looks promising so I look forward to hearing what you find.

> the good old problem of in-house legacy code, that depends on certain older versions of various toolkits, and such.

That's something I totally overlooked as my disciplinary area (geophysics and broadly geoscience)  seems to be just now jumping on board with VTK/ParaView as 3D visualization tools. So they're eager to try out the latest software and don't have any legacy code from previous PhD projects, etc., on which they depend... with that in mind, I'll remain open to providing a link to a tool, like `pyvtk`, that could parse the data out to legacy formats.

On this note, you haven't had any issues reading legacy formats into PyVista, have you?
