### ISSUE TITLE
Point Pick " pl.enable_point_picking" accuracy issues.

### ISSUE THREAD

**Issue by ndahiya3** [pyvista/pyvista#2856]
### Discussed in https://github.com/pyvista/pyvista/discussions/2825

<div type='discussions-op-text'>

<sup>Originally posted by **ndahiya3** June 19, 2022</sup>
I am trying to build an application for selecting landmark points on a surface (potentially multiple surfaces in the same view). But the accuracy of picked points seems to be way off. The actual point shows up super far away compared to where I click. There are clearly a bunch of points close to the mouse location but none of them seem to be picked. The picked point is literally on the other side of the surface which is not even visible. I have a couple of screenshots to illustrate. This is example the problem is really with actual use case with multiple surface. The screenshots are with pyvista plotter, but in my actual application, I am using pyvistaQT, QtInteractor, but the problem seems to be in both cases.

I see that there is a 'tolerance' parameter in the 'enable_point_picking' function but it doesn't seem to really help.

This is the place where I am trying to click:
![Point_pick_click_position](https://user-images.githubusercontent.com/15024623/174496427-a8fdd1d6-4453-4292-b466-b4a55551d057.png)

This is the place where the point shows up (other side of the surface). In other cases, it's much severe. The point is nowhere close to click location.
![Point_Pick_Actual_Position](https://user-images.githubusercontent.com/15024623/174496432-03de3903-8e8a-4ab6-b2f3-cae13ad7dd3b.png)
</div>

**Comment by tkoyama010** [comment]
Deplicate with https://github.com/pyvista/pyvista/discussions/2825

**Comment by ndahiya3** [comment]
It's duplicate because I created an issue from a discussion. Is that not allowed? I think this is a bug in the functionality.

**Comment by tkoyama010** [comment]
@ndahiya3  Thank you for your comments. We are closing the direct conversion from Discussion due to the following reasons:
1. Multi-posting with Discussion may confuse the discussion.
1. It does not follow the format of the issue, so it may not contain the necessary information for the developers.
If you want to report a new bug, we recommend that you submit it in [the format recommended by the community](https://github.com/pyvista/pyvista/issues/new?assignees=&labels=bug&template=bug-report.yml).
