### ISSUE TITLE
``UnstructuredGrid.cast_to_polydata`` is missing

### ISSUE THREAD

**Issue by germa89** [pyvista/pyvista#3009]
### Describe the feature you would like to be added.

So far, the method to convert unstructured grid to polydata seems to be missing.

I propose to implement that method, either directly or using pointset class as a bridge. I.e.

```py
UnstructuredGrid.cast_to_pointset().cast_to_polydata()
```

Probably using the pointset class generates overhead. On the other side, you "externalize the work to other functions.

**Comment by germa89** [comment]
Using ``pointset`` will only keep the points. So it is better to avoid intermediate classes.

**Comment by akaszynski** [comment]
You can't quite cast an unstructured grid to a polydata because the way they represent topology is different. Unstructured grids can contain solid cells whereas polydata can contain only points, lines, and faces.

I'd use [extract_surface](https://docs.pyvista.org/api/core/_autosummary/pyvista.UnstructuredGrid.extract_surface.html) as it will actually convert the exterior faces on an unstructured grid.

**Comment by AlexanderJuestel** [comment]
Hey, 

just as a follow up, the method @akaszynski proposed works. I have an unstructured grid which I want to export to use in QGIS as raster. Using ```extract_surface``` allows me to use ```ray_trace``` and to get a NumPy array that I can easily export to a raster.

This issue helped me a lot ;) 

![image](https://user-images.githubusercontent.com/45469915/207650790-f625f77b-b897-4989-94c9-40b1da210a79.png)

![image](https://user-images.githubusercontent.com/45469915/207650834-26997966-e98d-4292-8c9b-8f082589fc26.png)

![image](https://user-images.githubusercontent.com/45469915/207793692-dc8b8ac6-547b-402a-9980-d5ef3d1678d8.png)
