### ISSUE TITLE
possible bug in examples and feedback

### ISSUE THREAD

**Issue by marcomusy** [pyvista/pyvista#301]
Hi, while playing with the examples i've run into an error message

- [x]  in `examples/02-plot/cmap.py`
```
Traceback (most recent call last):
  File "cmap.py", line 54, in <module>
    p.add_mesh(mesh, cmap="fire", lighting=True, stitle="Colorcet Fire")
  File "/home/musy/soft/anaconda3/lib/python3.6/site-packages/pyvista/plotting/plotting.py", line 752, in add_mesh
    cmap = get_cmap_safe(cmap)
  File "/home/musy/soft/anaconda3/lib/python3.6/site-packages/pyvista/plotting/colors.py", line 391, in get_cmap_safe
    cmap = get_cmap(cmap)
  File "/home/musy/soft/anaconda3/lib/python3.6/site-packages/matplotlib/cm.py", line 182, in get_cmap
    % (name, ', '.join(sorted(cmap_d))))
ValueError: Colormap fire is not recognized. Possible values are: Accent, Accent_r, Blues, Blues_r, BrBG, BrBG_r, BuGn, BuGn_r, BuPu, BuPu_r, CMRmap, CMRmap_r ...
```
i'm maybe missing some package?

- [x]  i also get a seg fault from `examples/02-plot/scalar-bars.py` , right after the script ends (?!).

- [x] in `examples/02-plot/volume.py` I get a blank image when using keyword `mapper='gpu'`
(is there any good reason to prefer vtkFixedPointVolumeRayCastMapper over vtkOpenGLGPUVolumeRayCastMapper?)
![Screenshot from 2019-07-09 16-23-09](https://user-images.githubusercontent.com/32848391/60896213-3b7e2f00-a266-11e9-9170-d6afdb0d573a.png)

- [x] also, in addition to `opacity='linear'`, you might allow the user to define a transfer function for opacities by explicitly setting their values along the scalar range, e.g. something like `opacity=[0,0.2,0.9,0.2,0.1]` (see [here](https://github.com/marcomusy/vtkplotter/blob/master/examples/volumetric/read_vti.py)).

- [x] in `01-filter/glyphs.py`, when one uses keyword `subset=0.05` the resulting sampling looks non-uniform... one possible way out is to use the vtkCleanPolydata filter setting a non-zero tolerance (see [here](https://github.com/marcomusy/vtkplotter/blob/master/examples/basic/glyphs.py))

- [ ] in `00-load/create-geometric-objects.py` i see some feature (which i also get in vtkplotter btw) where the edge lines look awkward:
![Screenshot from 2019-07-09 15-34-50](https://user-images.githubusercontent.com/32848391/60897699-d11abe00-a268-11e9-851f-a82d2e984c7e.png)
not sure if this can relate to [this](https://vtk.org/doc/nightly/html/classvtkMapper.html#ad49f0d5f3086b3a79f542cb9e801d8ac) mapper method.. I never tried it..

Cheers,
Marco

**Comment by banesullivan** [comment]
Hi @marcomusy - Thanks for taking the time to play around with our examples!

### Colormaps

>  examples/02-plot/cmap.py ... [missing `'fire'` cmap]

The `'fire'` cmap belongs to [`colorcet`](). If you install colorcet then it should be available. Thanks for pointing out that it's not clear why the colormap isn't avaialble. I just edited that example to explicitly say that we can use colormaps from `colorcet` and `cmocean` *if* those packages are installed (reference #271) and implemented in d6e0f130a435fd81ef50822380761d0278403224


### Scalar Bars Seg Fault

> i also get a seg fault from `examples/02-plot/scalar-bars.py`, right after the script ends (?!).

That's not good! I will investigate... maybe this is linked to #185. In the meantime could you share your system details with:

```py
>>> import pyvista as pv
>>> print(pv.Report())
... copy paste this output
```

I am not experiencing this on my machine... my best guess is something is wrong with the memory cleanup. Have you run all the examples - is this the only one that segfaults?

### Volume Mapper

> in examples/02-plot/volume.py I get a blank image when using keyword mapper='gpu'
(is there any good reason to prefer vtkFixedPointVolumeRayCastMapper over vtkOpenGLGPUVolumeRayCastMapper?)

I couldn't figure this out which is why I implemented an option for users to specify which volume mapper they'd like to use. In my experience, the default `vtkFixedPointVolumeRayCastMapper` works on Mac, Linux, and Windows with/without a GPU. I set this as default so that the volume rendering would work for most people. I too have a weird result that looks the same as your image when using the `vtkGPUVolumeRayCastMapper` which I attributed to hardware compatibility issues on the VTK side, but I'm not sure (I have a Radeon Pro Vega 20 GPU and assumed VTK favors NVIDIA). I figured the safest default was `vtkFixedPointVolumeRayCastMapper` - do you use/do something different in `vtkplotter`?

There's also a high likeliehood that I implemented something wrong which is why only one of the mappers is working properly.

### Opacity Mappings

> also, in addition to opacity='linear', you might allow the user to define a transfer function for opacities by explicitly setting their values along the scalar range, e.g. something like opacity=[0,0.2,0.9,0.2,0.1]

That's an excellent idea! I'll see if I can put this in a new pull request. With that specific example, would I uniformly place those opacities across the scalar range? I.e. 0.0 at the min, 0.9 at the middle, and 0.1 at the max?


### Glyph Subsets

> in 01-filter/glyphs.py, when one uses keyword subset=0.05 the resulting sampling looks non-uniform... one possible way out is to use the vtkCleanPolydata filter setting a non-zero tolerance (see here)

That's definitely an artifact of how I implemented the "uniform subsetting" which I was hoping to fix once someone suggested a better way to subset the input mesh. See https://github.com/pyvista/pyvista/pull/269#issue-290455330:

> @banesullivan: note this is a uniform sampling of the points array, not a uniform distribution in space


I really like the way ParaView subsets the meshes but haven't had time to implement a similar solution.

## Awkward Edges

> in 00-load/create-geometric-objects.py i see some feature (which i also get in vtkplotter btw) where the edge lines look awkward

I'm not seeing the same thing... maybe this is a hardware issue with VTK? Could you share your GPU infromation as well as the versions report from above?

**Comment by marcomusy** [comment]
Hi Bane, this is my system report:
```
--------------------------------------------------------------------------------
  Date: Tue Jul 09 18:30:14 2019 CEST
  Platform: Linux-4.15.0-54-generic-x86_64-with-debian-buster-sid

             12 : CPU(s)
         x86_64 : Machine
          64bit : Architecture
        31.1 GB : RAM

  3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34)  [GCC 7.3.0]

         Python : Environment

         0.21.0 : pyvista
          8.1.2 : vtk
         1.16.4 : numpy
          2.3.0 : imageio
          1.4.3 : appdirs
          0.2.2 : scooby
          3.0.2 : matplotlib
            5.6 : PyQt5
          6.4.0 : IPython
          7.4.2 : ipywidgets

  Intel(R) Math Kernel Library Version 2018.0.2 Product Build 20180127 for
  Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```
and GPU info:
```
  *-display                 
       description: VGA compatible controller
       product: GP106 [GeForce GTX 1060 6GB]
       vendor: NVIDIA Corporation
       physical id: 0
       bus info: pci@0000:01:00.0
       version: a1
       width: 64 bits
       clock: 33MHz
       capabilities: pm msi pciexpress vga_controller bus_master cap_list rom
       configuration: driver=nvidia latency=0
       resources: irq:149 memory:eb000000-ebffffff memory:a0000000-afffffff memory:b0000000-b1ffffff ioport:e000(size=128) memory:c0000-dffff
  *-display
       description: Display controller
       product: Intel Corporation
       vendor: Intel Corporation
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 00
       width: 64 bits
       clock: 33MHz
       capabilities: pciexpress msi pm bus_master cap_list
       configuration: driver=i915 latency=0
       resources: iomemory:2f0-2ef irq:150 memory:2ffe000000-2ffeffffff memory:90000000-9fffffff ioport:f000(size=64)
```
maybe some settings i have is causing the artifact of the brown cube..

- Glyph Subsets: the `vtkCleanPolyData` tolerance did the trick for me :)

- Opacity Mappings: yes! i think that is a pretty intuitive option ... 

- Volume Mapper: it's a good point.. but i also have a very old laptop where i also test my examples from time to time and i dont remember that `vtkGPUVolumeRayCastMapper` (default for vtkplotter) is failing..i'll check again...!

- Segmentation fault: Yes - that is the only case where I got that.

Cheers,
m.

**Comment by banesullivan** [comment]
Thanks for all the feedback @marcomusy! I'll investigate the lingering issues, implement the suggested features, and poke around `vtkplotter`'s source to see what are that differences in our volume rendering to figure out why `vtkGPUVolumeRayCastMapper` might not be working

Also... how did you make such a comprehensive report of the GPU and display? Is there a Python package for that? I'm asking because I need to implement something like that in [`scooby`](https://github.com/banesullivan/scooby) (see https://github.com/banesullivan/scooby/issues/1)

**Comment by marcomusy** [comment]
oh that was from terminal command:
`lshw -C display`

**Comment by banesullivan** [comment]
Ah, thanks for the tip!

**Comment by marcomusy** [comment]
..another one is 
```
~ > nvidia-smi
Tue Jul  9 19:01:01 2019       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.54                 Driver Version: 396.54                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 106...  Off  | 00000000:01:00.0  On |                  N/A |
| 42%   34C    P5    10W / 120W |    673MiB /  6077MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0      1730      G   /usr/lib/xorg/Xorg                           432MiB |
|    0      5323      G   /usr/bin/gnome-shell                         143MiB |
|    0      6494      G   ...quest-channel-token=3282862331077601372    94MiB |
+-----------------------------------------------------------------------------+
```

**Comment by banesullivan** [comment]
Figured out the volume rednering issue - it has to do with the blending mode choice. Right now our default is "additive" and `vtkplotter`'s is "composite". With the "composite" mode, the `vtkGPUVolumeRayCastMapper`, `vtkOpenGLGPUVolumeRayCastMapper`, and `vtkSmartVolumeMapper` all work perfectly. 

I just changed the default volume rendering parameters to use the `vtkSmartVolumeMapper` and the "composite" blending mode (implemented in 959ba5e7b8718e5ef9f5fe9fef9c1a3910c03481)

**Comment by banesullivan** [comment]
`vtkSmartVolumeMapper` wasn't working on Windows so I switched it back to `vtkFixedPointVolumeRayCastMapper` but the default parameter for the blending should mitigate the issue above.

**Comment by banesullivan** [comment]
Got the opacity request implemented in #297

**Comment by banesullivan** [comment]
Fixed the segfault after `examples/02-plot/scalar-bars.py` in a252c0d42d859536cc09e3c3f94e212b92d5ade0

**Comment by banesullivan** [comment]
I'm not sure how to address the awward edges mentioned in the post above. If this is a problem, I recommend we make a new issue for it.

Otherwise, it appears everything here has been resolved

**Comment by banesullivan** [comment]
@marcomusy - does adding the following anywhere after importing VTK fix the geometry issue you saw?:

```py
vtk.vtkMapper.SetResolveCoincidentTopologyToPolygonOffset()
```

**Comment by marcomusy** [comment]
![image](https://user-images.githubusercontent.com/32848391/62330008-bc23fa00-b4b7-11e9-99bd-be38f333ca5e.png)
looks like it's still there..

**Comment by banesullivan** [comment]
Strange - have you tried making a minimal, pure-VTK example and posting this to the VTK discourse?

**Comment by marcomusy** [comment]
yep, that could be an idea although the problem is quite minor

**Comment by banesullivan** [comment]
One of these methods on `vtkMapper` should fix it:

```
 'SetResolveCoincidentTopology',
 'SetResolveCoincidentTopologyLineOffsetParameters',
 'SetResolveCoincidentTopologyPointOffsetParameter',
 'SetResolveCoincidentTopologyPolygonOffsetFaces',
 'SetResolveCoincidentTopologyPolygonOffsetParameters',
 'SetResolveCoincidentTopologyToDefault',
 'SetResolveCoincidentTopologyToOff',
 'SetResolveCoincidentTopologyToPolygonOffset',
 'SetResolveCoincidentTopologyToShiftZBuffer',
 'SetResolveCoincidentTopologyZShift'
```
