### ISSUE TITLE
Weight geodesic calculations by edge length

### ISSUE THREAD

**Issue by p-j-smith** [pyvista/pyvista#3188]
### Describe the feature you would like to be added.

Hi, it would be really nice to be able to weight the shortest path calculations in `PolyData.geodesic` and `PolyData.geodesic_distance` by the edge length between vertices.

I'm not sure how best to incorporate this into pyvista, but I'd be happy to contribute it with a little guidance. Thanks!

### Links to VTK Documentation, Examples, or Class Definitions.

It looks like there is an (experimental) option for this in vtk: https://vtk.org/doc/nightly/html/classvtkDijkstraGraphGeodesicPath.html#a7181bcce1675a88b5c8d9e6c3ca84e88

**Comment by adeak** [comment]
> Hi, it would be really nice to be able to weight the shortest path calculations in `PolyData.geodesic` and `PolyData.geodesic_distance` by the edge length between vertices.

When I read this, "edge length" sounds like the actual length of a given edge, and I would assume that Dijkstra already takes this into consideration, finding an overall shortest path.

The linked experimental feature has "scalars" in the name, so I assume it uses scalars instead of physical distance to weight a given edge. (Not sure how it considers scalars, since we only have point and cell scalars, and a surface doesn't typically have edge scalars.) So my point is, can you define the use case (the exact semantics) that you'd like from this feature?

**Comment by p-j-smith** [comment]
Yep you're right - for some reason I assumed the edge length was not taken into account, and only the number of edges was considered. But this is not the case. Sorry for the confusion.

**Comment by adeak** [comment]
OK, but again: which behaviour is this feature request about? The one that's already the behaviour, or what #3189 is opened for?

**Comment by p-j-smith** [comment]
Sorry, it's for the one that's already the behaviour
