### ISSUE TITLE
Coincident topology issues with pythreejs jupyter_backend

### ISSUE THREAD

**Issue by leilakany** [pyvista/pyvista#3482]
### Describe the bug, what's wrong, and what you expected.

Hello,

I have an issue when visualising thin shells. When looking at the normals in the screen recording attached, the values seem incorrect, but the problem disappears when zooming in. Have you encountered this before? Is there a way to fix this?

### Steps to reproduce the bug.

Try to visualize a mesh with a thin shell.

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Oct 17 14:57:25 2022 UTC

                OS : Linux
            CPU(s) : 8
           Machine : x86_64
      Architecture : 64bit
               RAM : 54.9 GiB
       Environment : Jupyter
        GPU Vendor : Mesa/X.org
      GPU Renderer : llvmpipe (LLVM 12.0.0, 256 bits)
       GPU Version : 4.5 (Core Profile) Mesa 21.2.6

  Python 3.8.10 (default, Mar 15 2022, 12:22:08)  [GCC 9.4.0]

           pyvista : 0.33.2
               vtk : 9.0.1
             numpy : 1.19.5
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.7
        matplotlib : 3.3.4
           IPython : 7.16.1
        ipyvtklink : 0.2.2
             scipy : 1.8.1
              tqdm : 4.60.0
            meshio : 4.4.1
--------------------------------------------------------------------------------
```

### Screenshots

https://user-images.githubusercontent.com/37087741/196212363-5df2c0a6-f7ee-4a28-9976-81cee8e9e692.mov

**Comment by banesullivan** [comment]
Ooof, that does not look good. Can you provide more details?

- Is this rendering in a PyVista render window or with one of the notebook rendering back ends?
- Are there multiple geometries in the scene? I suspect there is and we're seeing coincident topology not properly being handled.

> Try to visualize a mesh with a thin shell.

I'm not too sure what this actually means... Can you share the data in question and the code to make this visualization? Or perhaps some similar data?

**Comment by leilakany** [comment]
Absolutely, sorry for the missing information.
I am running this code in a jupyter notebook using pythreejs backend.
There is only one geometry in this scene, that is a plan.

Here are the code and the input file: 

```
import pyvista as pv
filename =  "/path/to/file/plan.stl"
mesh = pv.read(filename)
normals = mesh.point_normals
plotter = pv.Plotter()
plotter.add_mesh(mesh, scalars=normals[:, 1])
plotter.show(jupyter_backend='pythreejs')
```

[plan.stl.zip](https://github.com/pyvista/pyvista/files/9803221/plan.stl.zip)

**Comment by banesullivan** [comment]
**Good news:** I am able to reproduce this issue.

**Bad news:** I don't think this is something we can address.

This appears to be a conincident topology issue with rendering in three.js, not VTK or PyVista.

The `pythreejs` `jupyter_backend` is effectively exporting the PyVista/VTK scene to three.js and we do not support any custom rendering techniques once you get to three.js.

That's probably not what you want to hear, and I'm sorry to be dismissive of your problem here but we've been experiencing all kinds of issue with the `pythreejs` rendering backend lately - so much so that I'm chiming in on a lot of issues stating "we do not plan to support pythreejs long term."

**Hopeful news:** We are diligently working to create a notebook rendering backend developed for and by PyVista that will leverage VTK.js. This will have better synchronization of what's in the VTK renderer you create with a `pyvista.Plotter` and hopefully will advoid these nuanced issues. Unfortunately this isn't implemented yet, but it's something I'm actively working on and seeing issues like yours is a helpful nudge for me to implement it

**Comment by leilakany** [comment]
All right, thank you for looking into and and for the feedback.

Looking forward to this new notebook backend!

**Comment by leilakany** [comment]
Hello,
Coming back to you about this new notebook rendering backend. Do you have any estimated time of release for it?

**Comment by banesullivan** [comment]
> Do you have any estimated time of release for it?

Not exactly... I'm hoping before End of Year for a conservative timeline but hopefully sooner.

The work *is in progress* at this point. There is a very, very rough prototype in #3385
