### ISSUE TITLE
Bug with `clear_plane_widgets()`

### ISSUE THREAD

**Issue by wshinigamic** [pyvista/pyvista#3493]
### Describe the bug, what's wrong, and what you expected.

After calling Plotter.clear_plane_widgets(), the plotting window crashes with error message "zsh: segmentation fault".

See minimal example below to reproduce the bug.

### Steps to reproduce the bug.

```python
import pyvista as pv
from pyvista import examples

mesh = examples.download_doorman()

pl = pv.Plotter()
pl.add_mesh(mesh)
pl.add_plane_widget(None)
pl.clear_plane_widgets()
pl.show(cpos = 'xy')
```

### System Information

```shell
Date: Thu Oct 20 12:18:37 2022 +08

                OS : Darwin
            CPU(s) : 10
           Machine : arm64
      Architecture : 64bit
       Environment : Python
        GPU Vendor : Apple
      GPU Renderer : Apple M1 Pro
       GPU Version : 4.1 Metal - 76.3

  Python 3.9.6 (default, Aug  5 2022, 15:21:02)  [Clang 14.0.0
  (clang-1400.0.29.102)]

           pyvista : 0.37.dev0
               vtk : 9.2.2
             numpy : 1.23.4
           imageio : 2.22.1
           appdirs : 1.4.4
            scooby : 0.5.12
        matplotlib : 3.6.1
           IPython : 8.5.0
             scipy : 1.9.2
              tqdm : 4.64.1
```

**Comment by adam-grant-hendry** [comment]
@wshinigamic Thanks for reporting this! Per [Issue #3502](https://github.com/pyvista/pyvista/issues/3502), a current workaround is to first turn `Off()` the widget prior to using `clear_plane_widgets()`. The `clear()` functions in the ` pyvista` [`widgets`module](https://github.com/pyvista/pyvista/blob/068e4922742060bfe4f524955edb4ec7f4ee9782/pyvista/plotting/widgets.py) simply clear a `list` member containing all widgets of a given type. The crash is repeatable and likely due to the fact that the widget is still referenced by the `plotter`.

The following should fix your current situation until a permanent fix is employed:

```python
import pyvista as pv
from pyvista import examples

mesh = examples.download_doorman()

pl = pv.Plotter()
pl.add_mesh(mesh)
widget = pl.add_plane_widget(None)
widget.Off()
pl.clear_plane_widgets()
pl.show(cpos = 'xy')
```

![image](https://user-images.githubusercontent.com/59346180/198904865-c299d41f-5b7b-479f-8b3e-216be956b8a3.png)

**Comment by adam-grant-hendry** [comment]
Cc @banesullivan @akaszynski

**Comment by banesullivan** [comment]
It's pretty clear that all the clearing methods for the widgets need to call `Off` -- this should be a straight forward PR if either of you want to give it a go
