### ISSUE TITLE
Regressions on plots with latest version of pyvista (0.21.3)

### ISSUE THREAD

**Issue by xavArtley** [pyvista/pyvista#356]
Hi I have a problem only with the last version of pyvita (0.21.3).
Version 0.21.2
![image](https://user-images.githubusercontent.com/18531147/62620110-b3e51800-b918-11e9-9248-fa98f3dc513d.png)

Same code but with latest pyvista version (0.21.3)
The output is now a screenshot and the actors are not summed there is no cube anymore
![image](https://user-images.githubusercontent.com/18531147/62620262-25bd6180-b919-11e9-9e07-630806b6bc88.png)

**Comment by banesullivan** [comment]
Hi @xavArtley - we're aware of this issue and it was fixed in 803b64419488d1e21499ae86608654a57ffed2f5.

I also have a PR going in #349 to make the `+` operator work for all mesh types which is what I'm waiting on for the release to patch this. Considering this bug on `0.21.3` is pretty bad, I'll go ahead and move forward with #349 and push a release today.

**Comment by banesullivan** [comment]
@xavArtley - this is resolved on version `0.21.4` which is live on PyPI and hopefully conda-forge refreshes soon here

**Comment by xavArtley** [comment]
Thx

Le jeu. 8 août 2019 à 00:33, Bane Sullivan <notifications@github.com> a
écrit :
