### ISSUE TITLE
Plotter context manager?

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#3948]
### Describe the feature you would like to be added.

Would anyone want to be able to use a Plotter in a context manager? Would this even make sense?  See pseudocode below

### Implementation

We could implement this easily with these additional methods on the `BasePlotter` class:

```py
    def __enter__(self):
        """Enter context manager: ``with pv.Plotter() as pl:``"""
        return self

    def __exit__(self, *args, **kwargs):
        """Safely exit context manager handling any exceptions."""
        self.close()
```

Originally, I was thinking as the context manager exits, we could call `show()`, but I think we have to close out the plotter with this use case as if an error occurs, the `__exit__` is called.

### Pseudocode or Screenshots

```python
import pyvista as pv

with pv.Plotter() as pl:
    pl.add_mesh(pv.Sphere())
    pl.add_axes()
```

**Comment by adeak** [comment]
My knee-jerk reaction would be that I find it hard to see the use case, because the suggested example is more verbose than what we have now: the `with` statement obfuscates the `pl = pv.Plotter() assignment, adds indentation that doesn't seem quite natural (I usually have computation logic interspersed with plotting logic, but stuffing everything into the context manager would not be nice), and we're mostly sparing the manual call to `pl.close()` in most cases.

But thinking about a bit it seems a valid point that `Plotter`s are a resource that have to be managed, so cleanup even in case of errors (especially letting go of large associated meshes, closing videos etc.) is a solid use case. Although I'd expect that when a plotting script runs into an exception there will either be a `try` before the next plot and the developer should handle cleanup at that point, or the exception will bubble up and stop execution, in which case there isn't much delay before the plotter is cleaned up.

So I think there's a legitimate use case from the resource management perspective, but I'm not sure how often this would actually need to be triggered in the wild, and I'm also unsure whether end users would know about the feature and be willing to use it in their code. So to me it could go either way.

**Comment by banesullivan** [comment]
I agree -- the use case is just too weird. Closing
