### ISSUE TITLE
Add support for previous behaviour of Plotter.add_lines

### ISSUE THREAD

**Issue by p-j-smith** [pyvista/pyvista#4065]
### Describe the feature you would like to be added.

Hi, I've just been trying out the latest release and have noticed that the behaviour of `Plotter.add_lines` has changed to match the description in the docs (see #3667). Previously, `pyvista.lines_from_points` was used to generate the lines, whereas now `pyvista.line_segments_from_points` is used.

I've been using `Plotter.add_lines` with the previous (incorrect) behaviour and found it super useful. It would be great if this was supported, either as a new function e.g. `Plotter.add_lines_from_points` or as an argument to `Plotter.add_lines` e.g. `Plotter.add_lines(from_points=True)`

Thanks!

**Comment by banesullivan** [comment]
Consequences like this are an unfortunate part of maintaining such a robust API. I'm sorry that this change broke how you were using the method and that we did not provide a deprecation warning for this "incorrect/inconsistent" usage pattern.

> It would be great if this was supported ...

I don't know if we'll be able to support this, and it may be one of many features we have to turn down to avoid feature bloat. **_If you open a PR with the `from_points=True` argument exposed, I bet we could get this in for you, though._**

-----

**Bigger picture in my head (not representative of all PyVista devs):**

I'm advocating to start removing many of the `add_<special_type>()` methods from the `Plotter` class in favor of having users leverage the more standard and consistent `add_mesh()` and `add_volume()` methods... which I would love to one day merge into a single `add()` method! Under this paradigm, users would always work directly with mesh objects (often constructed from the same helper utilities we were using under the hood if passing line points). The Plotter API would then step away from trying to guess how to handle arbitrary NumPy arrays that a user is passing. Overall, this would move us toward a more explicit API where how the Plotter handles data matches what is expected. Otherwise, we end up with many possible ways in which a user may want to pass their numpy arrays representing `<special_type>` (lines in this example), and we cannot support all of them in one `add_<special_type>()` method without obfuscating the API. The same goes for all of the `update_<special_attribute>()` methods too. See also https://github.com/pyvista/pyvista/issues/3806

Sorry for the opinionated response, I hope this doesn't discourage you! I appreciate your feedback and letting us know we broke something you have been using for a while -- this is a valuable insight for us to consider while designing and refactoring these APIs.

**Comment by p-j-smith** [comment]
sorry for taking so long to get back to you, it took a little longer to get around to this than I planned

> Consequences like this are an unfortunate part of maintaining such a robust API.

that's totally understandable. It's inevitable these things will happen but I appreciate your reasoned response and the outline of your plans for pyvista!

**Comment by adeak** [comment]
@banesullivan arguably keeping the behaviour and fixing the docs would've been less invasive. And to me the old behaviour (requested here) makes a lot more sense. That being said, I'd consider the old behaviour to add a single "line", so `Plotter.add_line()`, which would indeed bloat the API. Creating separate polylines with the same helpers makes most sense to me.
