### ISSUE TITLE
Texture filtering

### ISSUE THREAD

**Issue by Kiord** [pyvista/pyvista#4178]
### Feature description

As far as know the only texture filtering available by default in PyVista is the nearest filter (equivalent to GL_NEAREST in OpenGL).
Even if it is the fastest filtering, the individual pixels of the texture are visible (image from PyVista doc):
![image](https://user-images.githubusercontent.com/79104227/227180253-765529d8-0b23-4a72-8d90-9a01d30ebf24.png)

It would be nice to add linear filtering or even texture mipmaps.

### Links to VTK Documentation, Examples, or Class Definitions.

Such a feature seems to be available in VTK but I don't know in what extent https://vtk.org/doc/nightly/html/classvtkTexture.html
I'm not sure what is currently used in PyVista and how it could be implemented.

**Comment by banesullivan** [comment]
These features are pretty easily accesible via VTK though not convienantly wrapped on PyVista's `Texture` implementation. Since PyVista objects are always thin wrappings of VTK objects, this is as simple as:

```py
import pyvista as pv
from pyvista import examples

# load a sample texture
tex = examples.download_masonry_texture()

# `tex` is `vtkTexture` instance
tex.InterpolateOn()

# create a surface to host this texture
surf = pv.Cylinder()

surf.plot(texture=tex)
```

| Interpolate Off | Interpolate On |
|---|---|
| ![screenshot (12)](https://user-images.githubusercontent.com/22067021/227550523-848e69c3-2ef5-4656-91c9-b175c5969126.png) | ![screenshot (13)](https://user-images.githubusercontent.com/22067021/227550812-d814407c-998f-44ef-9dfe-293891436a9f.png)

**Comment by banesullivan** [comment]
Looks like #4179 will improve this

**Comment by Kiord** [comment]
Thank you !
