### ISSUE TITLE
vtkTable wrapper

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#42]
I'm mulling over whether or not to implement a `vtkTable` wrapper in `vtki` and I'm curious about other's thoughts.

The `vtkTable` is a very common dataset I use and I have some functions in [PVGeo](https://github.com/OpenGeoVis/PVGeo) that will convert them back and forth to Pandas `DataFrame` objects (basically just tables with an awesome interface). 

My hesitations are:

1. `vtkTable`s are subclasses of `vtkDataObject`s not `vtkDataSet`s unlike everything else in `vtki`. This means we'd have to set up a new/separate module for DataObject wrappers.
2. We'd have to add Pandas as a dependency to the project (or maybe just an extra)
3. What would the interface look like? Would we build out a Pandas `DataFrame` with callbacks to the VTK data object?
4. Is this even worth doing considering it will be entirely different than everything else in `vtki` (as in it will be quite time consuming to get right)

**Comment by akaszynski** [comment]
I think adding an interface for ``vtkTable`` is a good idea.  I don't currently use ``vtkTable`` in any of my ``vtki`` dependent projects, but it's something to consider for storing tabular data using vtk.

I'm not familiar with ``vtkTable``, but I use pandas for another internal project and I think it's a great module to incorporate into ``vtki``, albeit optionally since not everyone would want to use that and it's quite a large dependency.  If we choose to add this, I'd make a new class that's a subclass of both the ``pandas`` ``DataFrame`` class and a ``vtkTable`` class.  The data should be acessable via both interfaces.

Whether it's worth it is up to you.  I don't use it, but if you do for ``PVGeo`` then it might be worth it to expose an interface so that others can use this functionality.  You'll have to provide examples in the docs on ``vtki`` explaining its usage.

**Comment by banesullivan** [comment]
I had another thought on this... Perhaps the dual inheritance with Pandas could come later and we could treat the `Table` interface very similar to the common data model with a new `RowDataDict` subclass of a dictionary just like how the `PointScalarsDict` and `CellScalarsDict` are implemented.

I think this would require a new `BaseObject` class at the top of all inheritance the refactor `vtki.Common` to `vtki.BaseDataSet`:

```
BaseObject
|__BaseDataSet
|      |_PolyData
|      |_ etc.
|__Table
|__MultiBlock
|__Texture
```

**Comment by banesullivan** [comment]
Note #202 might move this forward
