### ISSUE TITLE
Strictly enforce keyword arguments

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#427]
I see folks quite often forget the s in the `scalars` argument for the `BasePlotter.add_mesh()` method. We should allow `scalar` as an alias much like how we allow `rng` and `clim` for the colorbar range/limits

**Comment by agramfort** [comment]
I would disagree. 2 arguments:

`There should be one-- and preferably only one --obvious way to do it.` as says https://www.python.org/dev/peps/pep-0020/

it makes documentation harder.

**Comment by akaszynski** [comment]
Raise an exception to tell the user to use `scalars` when `scalar` is used as a keyword arg.

**Comment by banesullivan** [comment]
Okay, im convinced. 

We may want to do some keyword refactoring and not just allow an endless dict of `**kwargs` to be passed to `add_mesh`. For example, you can pass all types of typos and not have an error thrown:

```py
import pyvista as pv
p = pv.Plotter()
p.add_mesh(pv.Cube(), my_crazy_argument="foooooooo")
p.show()
```

There are several places in the API where this can happen that will need to be refactored

**Comment by banesullivan** [comment]
What we could do is pop out the allowed aliases like `rng` and then raise an exception if thee `kwargs` dict is not empty that might say something like:

> "`scalar`, [list of arguments still in the kwargs] is/are not a keyword arguments."

**Comment by banesullivan** [comment]
Anyone have time to review #432 which resolves this?

**Comment by akaszynski** [comment]
I think the reason why we chose to use `**kwargs` is due to the amount of time we'd have to invest to make sure the keyword arguments line up between functions.  When we change the keyword arguments, we have to change it in many places and it's a nightmare to keep track of, but it does mean that when we use an IDE, there's no autocomplete.  Even having written many of the original methods, I forget what the exact spelling of some of the kwargs and I find myself referencing the docs.

A combination of #432 and @agramfort 's approach would be ideal. It will mean some extra work, and I'm a bit busy at the moment to be able to really contribute this sort of pull request.  Still, I think it's a good direction to move in, especially considering the number of people using `pyvista`.

**Comment by banesullivan** [comment]
I’m mostly in agreement about avoiding `kwargs` and explicitly passing everything around except in one case: when we have a method with its own set of explicit keyword arguments and we take any additional kwargs and pass them directly to the `add_mesh` method. This is fairly common throughout the API and something I cannot justify implementing explicitly because the `add_mesh` method has a high amount of arguments. Also, we’re still sub-`v1.x` so the arguments to the `add_mesh` method are likely to change/increase and we would have to update them all over the API. I think it is reasonable to document those functions by specifying `kwargs` as a parameter and pointing users to the `add_mesh` docs

Maybe in #432 we could find all places throughout the API that use `kwargs` and refactor if they are not passing the them to the `add_mesh` method. That would mostly address @agramfort’s point and then the work in #432 would ensure no keyword argument goes unchecked/documented. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by banesullivan** [comment]
> Should @GuillaumeFavelier give a try to the autodocstring checks?

I like that checking - plus I think we need some sort of check to make sure the parameters to all methods are documented... many are not
