### ISSUE TITLE
Consider making imageio optional

### ISSUE THREAD

**Issue by akaszynski** [pyvista/pyvista#4302]
As pointed out in https://github.com/conda-forge/pyvista-feedstock/pull/76#issuecomment-1513899912, we might consider making `imageio` optional to encourage adoption by avoiding `ffmpeg`, which appears to contain codecs that Microsoft can't install.

Since @basnijholt is a Quantum Software Engineer working for Microsoft, and that sounds really cool, I think we should consider making `imageio` optional. We only use it in a handful of spots within PyVista and if if we just place an import guard over the functionality it adds, we can easily make it an optional install reqirement.

**Comment by banesullivan** [comment]
> and that sounds really cool,

More than enough justification for me! +1

This shouldn't be to bad to handle

**Comment by basnijholt** [comment]
Hi all 👋

Thanks a lot for starting this conversation! 

As far as I can see in the code that @MatthewFlamm linked above, `imageio` is already "optional" because it's only ever imported inside functions. I guess just moving this line:
https://github.com/pyvista/pyvista/blob/b9ee9b9c0625d737dfd4a60e9ed10609e7e0b7fd/pyproject.toml#L29
to the `all` section would suffice (maybe another section?).

**Comment by basnijholt** [comment]
I have just opened this https://github.com/pyvista/pyvista/pull/4333 where imageio becomes an optional dependency.
