### ISSUE TITLE
It would be better as a standalone `pyvista-planets` package

### ISSUE THREAD

**Issue by tkoyama010** [pyvista/pyvista#4526]
I'm not sure about this `planets` module overall. IMO, it would be better as a standalone `pyvista-planets` or `pyvista-examples` package. As it stands, this seems like a lot of code for examples that only a small minority of users leverage.

I agree the naming here isn't ideal. I do not want this PR to be the place to refine this and recommend opening an issue for follow-up work and discuss stripping this module out into a new `pyvista-examples` repo for instance

_Originally posted by @banesullivan in https://github.com/pyvista/pyvista/pull/4515#discussion_r1225539684_

**Comment by tkoyama010** [comment]
I have been creating a repository called [`pyvista-planets`](https://github.com/pyvista/pyvista-planets) for the past few days to separate the planet downloads. In the process, my mind started to think that it might be a good idea to rename this project `pyvista-download` and move all of pyvista's download functions there, once `pyvista-download` is mature enough to be released to PyPI, When `pyvista-download` is mature enough to be released to PyPI, I would like to deprecate under the PyVista example directory.

@pyvista/developers Please let me know what you think about this as it is a part of the overall design.

My hope is that PyVista will focus on the behavior of the plot itself, not the data download.

**Comment by larsoner** [comment]
I don't know what download functions are used here, but a few years ago MNE abandoned our internal data fetching code in favor of the `pooch` package and have had no problems with it. So if custom HTTP or FTP stuff is used currently I'd highly recommend switching

**Comment by akaszynski** [comment]
We also use pooch, and if I recall, we used mne as inspiration for this decision.

**Comment by tkoyama010** [comment]
You are right.
https://github.com/pyvista/pyvista/blob/7a9503032401124cf0a234dfa9783608bc92647c/pyvista/examples/downloads.py#L179

**Comment by banesullivan** [comment]
> I have been creating a repository called [pyvista-planets](https://github.com/pyvista/pyvista-planets) for the past few days to separate the planet downloads

Fantastic! Thank you for taking the initiative on this, @tkoyama010!

>  In the process, my mind started to think that it might be a good idea to rename this project pyvista-download and move all of pyvista's download functions there

I'm game for this, but personally, I think it should be `pyvista-examples`

> I would like to deprecate under the PyVista example directory.

Instead, we could ship `pyvista-examples` as a standalone package and let `pyvista.examples` be a namespace package effectively pointing to this. Avoiding the need for any deprecation. I would like to strongly advocate for this since the `pyvista.examples` subpackage has become widely used and demonstrated in our examples.

Generally, I'm up for this idea but my availability to help implement this is limited right now. I think it would be a great idea so we can add more example data with a higher cadence than PyVista's release cycle.

> My hope is that PyVista will focus on the behavior of the plot itself, not the data download.

As previous comments point out, we already do this using `pooch`. Our "downloads" code is simply a thin wrapper around `pooch` pointing to our datasets. This module is already pretty thin an lightweight.

**Comment by tkoyama010** [comment]
Thank you for your guidance and comments!

> I'm game for this, but personally, I think it should be pyvista-examples

I was hesitant to name the repository `pyvista-examples`, because there is already a repository called `pyvista-examples`, but I will go ahead with `pyvista-examples` as the package name (the repository will be `example`).

> Instead, we could ship pyvista-examples as a standalone package and let pyvista.examples be a namespace package effectively pointing to this. Avoiding the need for any deprecation. I would like to strongly advocate for this since the pyvista.examples subpackage has become widely used and demonstrated in our examples.

That's a very good way to avoid deprecation. +100 for it.

**Comment by MatthewFlamm** [comment]
What is the benefit of having a package that is imported into the pyvista namespace?  This means now we have to coordinate changes across two or more repositories. For example if we need to add data in `pyvista-examples` to be able to run tests in `pyvista`, we would now have to have changes in 3 repos, `vtk-data`, `pyvista-examples` and `pyvista`.  Often the docstring example in `pyvista-example` needs new functionality from `pyvista` to work.  It creates a chicken-egg problem.

**Comment by tkoyama010** [comment]
@MatthewFlamm 
Thank you for the excellent point.
The purpose of this proposal is to isolate the growing number of download codes that are not related to the functionality of PyVista. 
I believe that the burden will not change since the test code will be completely migrated to `pyvista-examples` in future pull-request updates, so the only repositories that will need to be changed are `vtk-data` and `pyvista-examples`.
`pyvista-examples` will be added to CI like PyVistaQT and GeoVista, so the test code will no longer be needed. I think that download codes that require new functionality can be managed in pyvista until that version is released, and then moved to `pyvista-examples` after the version is released.
Please point out any concerns with this content.

**Comment by MatthewFlamm** [comment]
The use case I'm thinking of is that someone wants to add a new Reader and would like to add a file for testing.  This would require the file to be added to `vtk-data`, then add the download function to `pyvista-examples` (note that the docstring example cannot get be added because the functionality to read the data is missing).  Then add the Reader to `pyvista`, then go back to `pyvista-examples` to update the docstring example.

This is a not a very common use case, but it isn't very rare either.

**Comment by tkoyama010** [comment]
This issue and PR will be closed as no effective solution can be provided for the indicated use case. If this issue becomes critical to the project, please help us to discuss it again.
