### ISSUE TITLE
Add option to select different timesets in Ensight reader

### ISSUE THREAD

**Issue by gilrrei** [pyvista/pyvista#4558]
### Describe the feature you would like to be added.

Currently the timeset ID in the EnSight reader is hard-coded to 0:
https://github.com/pyvista/pyvista/blob/3af50f08b8d9f317209e4f535d3d8ccbbcf7a715/pyvista/core/utilities/reader.py#L834-L838

However, the EnSight format allows for multiple timeseries which can currently not be selected. This is a problem for codes that write constant fields in time into timeset 0, such that the size of that timeset is 1. Consequently, time values besides 0 cannot be accessed by the reader. Locally this is quite easy to overwrite. My (feature request) questions are: Is this relevant for this project and if so, how to pass this option to the reader? I guess altering the interfaces/method signature is not desired.

**Comment by MatthewFlamm** [comment]
I think it is relevant for this project to provide the most flexible usage to read in data.  I'm not too familiar with this use of multiple time sets, but I'm imagining that you will have multiple time points per time set. We could first expose a property that returns the information about all the time sets like `[[0], [0, 1], [0, 1]]`, and then we need to decide how to handle the rest of the methods we have here.  At first thought, we could return the total number of unique time points in all time sets for `number_time_points` and all the unique values in `time_point_value`.

This would be a breaking change, but a positive one since it gives more flexibility to the user.

**Comment by MatthewFlamm** [comment]
All of the data files for testing that we currently have available either do not have time sets or have only 1 time set.  See https://github.com/pyvista/vtk-data/tree/master/Data/EnSight.  For implementing these features, it would be useful, if possible, to have a set of simple example data.

**Comment by gilrrei** [comment]
> All of the data files for testing that we currently have available either do not have time sets or have only 1 time set. See https://github.com/pyvista/vtk-data/tree/master/Data/EnSight. For implementing these features, it would be useful, if possible, to have a set of simple example data.

Providing some `.case` files with multiple timesets should not be a problem. Adding the examples to the example repo sounds like a reasonable first step.

**Comment by advktEntnschdl** [comment]
I stumbled upon the same issue, since our code also writes two time sets. To access the desired data (without modifying PyVista's EnSightReader) I have to delete the first time set by calling `reader.reader.GetTimeSets().RemoveItem(0)`. This is, however, undone by calling `reader.read()` and leads to rather ugly solutions when looping over time points.

Therefore I would greatly appreciate a solution to this issue.

Please find attached my [MWE: EnSightWithMultipleTimeSets.zip](https://github.com/pyvista/pyvista/files/13974908/EnSightWithMultipleTimeSets.zip) including an EnSight data base with two time sets.
