### ISSUE TITLE
Color mapping issues when volume rendering

### ISSUE THREAD

**Issue by banesullivan** [pyvista/pyvista#475]
#464 brought the volume rendering to general working order which was desperately needed, but some lingering issues remain around the color mapping.

The remaining issue appears to be with how we map the scalars - this results in issues if trying to use custom scalar bar limits as @keltonhalbert brought up in https://github.com/pyvista/pyvista/issues/430#issuecomment-548165868

Note that in `add_volume`, we copy the input dataset and do some weird stuff with the scalars.

https://github.com/pyvista/pyvista/blob/5851fae15096ceeba7c4040dad1c91f9428ee2e7/pyvista/plotting/plotting.py#L1484-L1485

The reason that values are not appearing outside the `clim` range is due to this snippet where we cast values outside the range to NaN:

https://github.com/pyvista/pyvista/blob/5851fae15096ceeba7c4040dad1c91f9428ee2e7/pyvista/plotting/plotting.py#L1595-L1602

For example, the same dataset and `clim` for a) PyVista and b) ParaView:

| PyVista | ParaView |
|---------|----------|
| ![download](https://user-images.githubusercontent.com/22067021/69659871-5a763580-103c-11ea-87f8-227dcc585dd4.png) | ![Screen Shot 2019-11-26 at 10 58 59 AM](https://user-images.githubusercontent.com/22067021/69659685-f489ae00-103b-11ea-98e3-79ff61f8cb1a.png) |

-----

# Next Steps

I propose we totally overhaul the `add_volume` method and refactor `add_mesh` as well so that the common code between the two is shared (per https://github.com/pyvista/pyvista/pull/464#issuecomment-557660113) and @keltonhalbert kindly volunteered to try (per https://github.com/pyvista/pyvista/pull/464#issuecomment-558731871)

## Things to address

- [ ] Do not copy the volume dataset
- [x] fix color bar limit issues
- [ ] fix color mapping issues when `n_colors` is low (categorical data)

**Comment by keltonhalbert** [comment]
I figured I'd start off simple while I'm getting familiar with the mesh and volume routines before diving straight into a refactor. I think the push I made to the branch results in the expected behavior. 
Instead of 
https://github.com/pyvista/pyvista/blob/5851fae15096ceeba7c4040dad1c91f9428ee2e7/pyvista/plotting/plotting.py#L1595-L1602
It is now
https://github.com/pyvista/pyvista/blob/4f2d71e98601e2e3753a3c8dd413094ec3be0822/pyvista/plotting/plotting.py#L1595-L1602

This ensures that the scalar data is mapped directly to the color range specified without removing the actual volumetric data. That means that the opacity curve is the only thing that dictates what is visible or not in the volume, which should be the expected behavior. Below is a before and after. 
![Selection_132](https://user-images.githubusercontent.com/1411265/70088428-21c2f700-160e-11ea-9afe-1793199eef23.png)
![Selection_131](https://user-images.githubusercontent.com/1411265/70088432-24255100-160e-11ea-87ca-c22c83719bdd.png)

**Comment by keltonhalbert** [comment]
I should note that this does not fix the issue with needing to make a copy of the dataset. I'd prefer a way to handle this that does not require this approach, but it's a start.

**Comment by akaszynski** [comment]
This dataset is beautiful!

**Comment by banesullivan** [comment]
This is looking awesome, @keltonhalbert!! That's a rather simple fix - good catch! It might be good to go ahead and create a PR for this fix so it lands on the soon coming `0.23.0` release, then worry about the refactoring for a later release

**Comment by banesullivan** [comment]
> This dataset is beautiful!

Seriously. 😲 

It would be cool for us to include something like that dataset in the show-room whenever I get around to actually building that website: https://github.com/pyvista/show-room

**Comment by banesullivan** [comment]
@keltonhalbert - can you quickly load that dataset in ParaView and volume render with the same cmap and limits to make sure it looks the same? It's probably easiest to just save the PyVista uniform grid you created using: `.save("foo.vti")`

**Comment by keltonhalbert** [comment]
Alright, I'll make a pull request with the changes so that they can go in the next release. Should be able to load up into ParaView no problem!

**Comment by banesullivan** [comment]
I think this has been resolved with the latest volume mapper additions. Either way closing due to staleness
