### ISSUE TITLE
`plot` does not show cell scalars by default when only cell scalars exist

### ISSUE THREAD

**Issue by user27182** [pyvista/pyvista#5461]
### Describe the bug, what's wrong, and what you expected.

Calling `add_mesh` or `mesh.plot()` does not plot the scalars when `n_points == n_cells` and when only cell scalars exist.

### Steps to reproduce the bug.

```python
import pyvista as pv
c = pv.Cone()
c.cell_data['ids'] = list(range(c.n_cells))

# These are the conditions needed to reproduce the bug
assert(c.n_cells == c.n_points)
assert(len(c.array_names) == len(c.cell_data.keys())) # only one scalar array is defined

c.plot()
```
Actual result
<img width="624" alt="image" src="https://github.com/pyvista/pyvista/assets/89109579/7b1305aa-842b-4faf-b634-070113978be1">

Expected result
<img width="624" alt="image" src="https://github.com/pyvista/pyvista/assets/89109579/d1af84c8-c448-425c-bc37-c4d2d9b0b6d1">

As a workaround, the expected result is obtained using `c.plot(preference='cell')`, but this should not be necessary since only cell scalars exist.

### System Information

```shell
Date: Fri Jan 12
                OS : Darwin
            CPU(s) : 8
           Machine : arm64
      Architecture : 64bit
               RAM : 16.0 GiB
       Environment : IPython
       File system : apfs
        GPU Vendor : Apple
      GPU Renderer : Apple M2
       GPU Version : 4.1 Metal - 83.1
  MathText Support : True
  Python 3.12.1 (v3.12.1:2305ca5144, Dec  7 2023, 17:23:38) [Clang 13.0.0
  (clang-1300.0.29.30)]
           pyvista : 0.44.dev0
               vtk : 9.3.0
             numpy : 1.26.3
        matplotlib : 3.8.2
            scooby : 0.9.2
             pooch : 1.8.0
            pillow : 10.2.0
           imageio : 2.33.1
           IPython : 8.20.0
          colorcet : 3.0.1
           cmocean : 3.0.3
        ipywidgets : 8.1.1
              tqdm : 4.66.1
            meshio : 5.3.4
    pytest_pyvista : 0.1.8
             trame : 3.5.1
      trame_client : 2.14.2
      trame_server : 2.15.0
         trame_vtk : 2.6.3
     trame_vuetify : 2.3.1
      nest_asyncio : 1.5.8
--------------------------------------------------------------------------------
```

**Comment by banesullivan** [comment]
I think the crux of this is that `c.n_points == c.n_cells` which is somewhat of an edge case.

It looks like there is a genuine bug here. After plotting, if we repr the mesh in a Jupyter cell it looks like something in the plotting routine got confused and set a new point_data array because the length matched (which is incorect):

<img width="1001" alt="Screenshot 2024-01-14 at 8 22 02 PM" src="https://github.com/pyvista/pyvista/assets/22067021/9ed8d9b0-0f79-4a46-9f85-65fc2d53fcef">

As an aside, this feels related to #1897

**Comment by banesullivan** [comment]
This bit of logic feels suspect to me:

https://github.com/pyvista/pyvista/blob/7636dc7b65fb8eb9fc986bb985d6405e96ec3d33/pyvista/plotting/mapper.py#L455-L460

I think `preference` defaults to  `'point'` and this bit of logic then thinks the scalars should be on the points... some further digging is needed

**Comment by MatthewFlamm** [comment]
This looks suspicious to me as well.  It seems like it is a bug in higher level design to me since this function takes in an `ndarray` rather than a `str`, so it cannot figure out whether the data is originally point or cell data in this ambiguous case.  I suspect we have to pass in a definitive `use_points` or similar and have logic in the calling function or a separate helper function to decide.


> This bit of logic feels suspect to me:
> 
> https://github.com/pyvista/pyvista/blob/7636dc7b65fb8eb9fc986bb985d6405e96ec3d33/pyvista/plotting/mapper.py#L455-L460

**Comment by MatthewFlamm** [comment]
https://github.com/pyvista/pyvista/blob/e84354e72acf6d69277954cdc0f16c739aab6897/pyvista/plotting/plotter.py#L3492-L3501

This part of the code is executed _before_ the `_configure_scalar_mode` in the `mapper` gets called in the example given in the issue.  One potential solution might be to reset the `preference` in this part of the code based on the scalar array found.  I'm also wary about the comment in this part of the code, so that is another avenue to explore

**Comment by banesullivan** [comment]
> "This should be refactored by 0.36.0"

🤣

**Comment by banesullivan** [comment]
> One potential solution might be to reset the preference in this part of the code based on the scalar array found.

I think this could work! Nice find!
