### ISSUE TITLE
multi_ray_trace Enhancement Proposal

### ISSUE THREAD

**Issue by natsuwater** [pyvista/pyvista#5587]
### Describe the feature you would like to be added.

The `multi_ray_trace` function in `PolyDataFilters` (located in `filters/poly_data.py`) currently handles retrying ray trace when Embree’s ray tracing fails. However, there is an issue with the current approach.

When retrying, the function creates a second point and invokes `ray_trace` from PyVista, using `origins_retry` and `second_points` as arguments. The calculation for `second_points` is as follows:

```
second_points = origins_retry + unit_directions * self.length
```

Here, `self.length` represents the size of the poly_data.

However, if `origins_retry` is significantly distant from the `poly_data` (beyond self.length), the line segments between `origins
_retry` and`second_points` do not necessarily intersect with `poly_data`. As a result, `ray_trace` may fail to find intersections.

To increase the likelihood of finding intersections, I propose changing the calculation for the second points as follows:

```
poly_data = self

direct = (
    (poly_data.bounds[0] + poly_data.bounds[1]) / 2.  - origins_retry[0],
    (poly_data.bounds[2] + poly_data.bounds[3]) / 2.  - origins_retry[1],
    (poly_data.bounds[4] + poly_data.bounds[5]) / 2.  - origins_retry[2]
)
second_points = origins_retry + unit_directions * (
    np.sqrt((direct[0] ** 2 + direct[1] ** 2 + direct[2] ** 2)) + poly_data.length)
    
```

The code here is meant to show the idea. I'm not sure `bounds` is suited for this purpose.

This change should improve the function’s ability to find intersections in a wider range of cases. 

### Pseudocode or Screenshots

The following code is based on `multi_ray_trace` to show that the choice of the second_points is import fo find intersections.

```python
import pyvista as pv
import numpy as np

sphere = pv.Sphere()

src = np.array([(10., 0., 0.)])
directions = np.array([(-1., 0.01, 0.01)])

origins_retry = src
directions_retry = directions

unit_directions = directions_retry / np.linalg.norm(
    directions_retry, axis=1, keepdims=True
)

second_points = origins_retry + unit_directions * sphere.length

for origin, second_point in zip(origins_retry, second_points):
    locs, indices = sphere.ray_trace(origin, second_point, first_point=True)
    print(locs) ##  "[]"

direct = (
    (sphere.bounds[0] + sphere.bounds[1]) / 2.  - origins_retry[0][0],
    (sphere.bounds[2] + sphere.bounds[3]) / 2.  - origins_retry[0][1],
    (sphere.bounds[4] + sphere.bounds[5]) / 2.  - origins_retry[0][2]
)
second_points = origins_retry + unit_directions * (
    np.sqrt((direct[0] ** 2 + direct[1] ** 2 + direct[2] ** 2)) + sphere.length)
                                                   
for origin, second_point in zip(origins_retry, second_points):
    locs, indices = sphere.ray_trace(origin, second_point, first_point=True)
    print(locs) ## "[0.48025852 0.09519742 0.09519742]"
```
Or drag your screenshot here!

**Comment by Keou0007** [comment]
This seems like a fairly small and simple change to make. Let me make sure I'm understanding correctly:

- The original code uses the self.length function (which returns the diagonal length of the bounding box) multiplied by the unit direction vector, to create the second point to ray trace to. The idea being that this length will be further than the distance from the origin point to any possible point in the dataset. But this assumes the origin points are located inside the bounding box of the dataset.
- If the origin points are outside the bounding box and far enough away, it's possible the line between the origin point and the second point won't intersect the data, even if a ray on that trajectory would eventually.
- The new code calculates the length of the vector between the origin point and the centre of the bounding box and adds it to the bounding box length, to ensure the second point will always be located on the other side of the bounding box from the origin point, even if that point is outside the box. Thus it removes the possibility of an intersection point being missed because the length of the search vector is too short.
