### ISSUE TITLE
pyvista.Plane results in approximate coordinates, slightly off prescribed ones

### ISSUE THREAD

**Issue by fmamitrotta** [pyvista/pyvista#5608]
### Describe the bug, what's wrong, and what you expected.

I want to mesh a rectangle in the cartesian y-z plane. Along the y-direction the rectangle has size `length` and along the z-direction it has size `height`. When I use `pyvista.Plane` to mesh the rectangle, the smallest y-coordinates of the points are not exactly what they are supposed to be, and they're slightly off. I believe this issue is similar to #4134 .

### Steps to reproduce the bug.

```python
import pyvista as pv
import numpy as np

y_0 = 0.  
length = 29380/18
height = 770.
no_elements = [2, 6]
plane1 = pv.Plane(center=[0, y_0 + length/2, 0], direction=[-1, 0, 0], i_size=height,
                  j_size=length, i_resolution=no_elements[0], j_resolution=no_elements[1])
print(np.sort(plane1.points[:, 1]))

y_0 = length
print(y_0)

plane2 = pv.Plane(center=[0, y_0 + length/2, 0], direction=[-1, 0, 0], i_size=height,
                  j_size=length, i_resolution=no_elements[0], j_resolution=no_elements[1])
print(np.sort(plane2.points[:, 1]))
```

This code returns the following:
```raw
[2.7126736e-05 2.7126736e-05 2.7126736e-05 2.7203702e+02 2.7203702e+02
 2.7203702e+02 5.4407404e+02 5.4407404e+02 5.4407404e+02 8.1611108e+02
 8.1611108e+02 8.1611108e+02 1.0881482e+03 1.0881482e+03 1.0881482e+03
 1.3601852e+03 1.3601852e+03 1.3601852e+03 1.6322222e+03 1.6322222e+03
 1.6322222e+03]
1632.2222222222222
[1632.2223 1632.2223 1632.2223 1904.2593 1904.2593 1904.2593 2176.2964
 2176.2964 2176.2964 2448.3333 2448.3333 2448.3333 2720.3704 2720.3704
 2720.3704 2992.4075 2992.4075 2992.4075 3264.4443 3264.4443 3264.4443]
```

The first elements of the first array should be exactly 0, and the first elements of the second array should be approximated to 1632.2222, NOT to 1632.2223.

What is happening here?

### System Information

```shell
--------------------------------------------------------------------------------
  Date: Mon Feb 12 14:35:13 2024 GMT Standard Time

                OS : Windows
            CPU(s) : 12
           Machine : AMD64
      Architecture : 64bit
               RAM : 31.8 GiB
       Environment : Python
        GPU Vendor : Intel
      GPU Renderer : Intel(R) UHD Graphics 630
       GPU Version : 4.5.0 - Build 30.0.101.1692
  MathText Support : False

  Python 3.9.17 (main, Jul  5 2023, 20:47:11) [MSC v.1916 64 bit (AMD64)]

           pyvista : 0.43.3
               vtk : 9.0.3
             numpy : 1.23.5
        matplotlib : 3.7.1
            scooby : 0.7.1
             pooch : Trouble importing
            pillow : 9.4.0
           imageio : 2.26.0
         pyvistaqt : 0.9.1
             PyQt5 : 5.15.7
           IPython : 8.10.0
        ipywidgets : 8.0.4
             scipy : 1.10.0
      nest_asyncio : 1.5.6

  Intel(R) oneAPI Math Kernel Library Version 2021.4-Product Build 20210904
  for Intel(R) 64 architecture applications
--------------------------------------------------------------------------------
```

**Comment by user27182** [comment]
I think this is a general numerical precision issue. I don't think the fix for #4134 has regressed.

Running:
```python -c "import pyvista;print(pyvista.Plane(direction=(0,1,0), i_resolution=1, j_resolution=1).points)"```
with `pyvista==0.41` yields:

```
[[-5.000000e-01 -5.551115e-17 -5.000000e-01]
 [ 5.000000e-01  5.551115e-17 -5.000000e-01]
 [-5.000000e-01 -5.551115e-17  5.000000e-01]
 [ 5.000000e-01  5.551115e-17  5.000000e-01]]
```

running the same command with `pyvista==0.43` yields:
```
[[ 0.5  0.   0.5]
 [ 0.5  0.  -0.5]
 [-0.5  0.   0.5]
 [-0.5  0.  -0.5]]
```

Not sure what exactly may be cause the loss of precision, but this probably isn't specific to `Plane`.

Using double precision may help, but by default the [vtkPlaneSource uses single precision](https://github.com/Kitware/VTK/blob/dc7ca002c211fdbff822d86dd51e553b6048c637/Filters/Sources/vtkPlaneSource.cxx#L45). A `kwarg` could be added to `pyvista.Plane` to use double precision instead but this would need to be implemented as a new feature. Feel free to submit a PR with these changes, we'll happily review it.

A workaround may be to first generate the Plane using default parameters, then convert the points to double precision (I think there is an undocumented `points_to_double` function somewhere in the pyvista code), and scale/rotate the plane manually afterwards, though I think you may still be stuck with values that are reflective of single precision.

(Note that in general creating a plane first, then rotating it explicitly is generally recommended anyway. The `direction` parameter is unstable, and may be deprecated in the future, see https://github.com/pyvista/pyvista/pull/5188)

**Comment by user27182** [comment]
I have identified the problem. This issue is the result of adding two arrays with the same value but different precision, e.g.:

``` python
val = 29380/36
x = np.float32(-val)
y = np.float64(val)
print(x+y)
2.712673608584737e-05
```

which is the error from zero reported in the first example. But yes, it should be zero.

The error stems from this line:
https://github.com/pyvista/pyvista/blob/29a6c87802b1aca52218f2db4d4077680bae272a/pyvista/core/utilities/geometric_sources.py#L58
where `np.array` will create a `float64` array, whereas `surf.points` is a `float32` array.

Changing this line to
 ``` python
surf.points += np.array(center, dtype=surf.points.dtype)
``` 
resolves the issue. The output after making this change is:

```
[   0.         0.         0.       272.037    272.037    272.037
  544.07404  544.07404  544.07404  816.1111   816.1111   816.1111
 1088.1482  1088.1482  1088.1482  1360.1852  1360.1852  1360.1852
 1632.2222  1632.2222  1632.2222 ]
1632.2222222222222
[1632.2222 1632.2222 1632.2222 1904.2592 1904.2592 1904.2592 2176.2961
 2176.2961 2176.2961 2448.3333 2448.3333 2448.3333 2720.3704 2720.3704
 2720.3704 2992.4072 2992.4072 2992.4072 3264.4443 3264.4443 3264.4443]
```

**Comment by tkoyama010** [comment]
Maybe related to #5411.
