### ISSUE TITLE
Add a `connectivity` filter based on shared faces

### ISSUE THREAD

**Issue by GuillaumeBroggi** [pyvista/pyvista#6649]
As detailed in the [pyvista.datasetfilters.connectivity documentation](https://docs.pyvista.org/api/core/_autosummary/pyvista.datasetfilters.connectivity):
> In general, cells are considered to be connected if they share a point.

Some use cases require cells to be connected if and only if they share faces. I am not sure how such a filter could be implemented.

**Comment by user27182** [comment]
I believe that limitation exists because the `connectivity` filter is general-purpose. If we look at connectivity for structured meshes like ImageData, 6-connectivity can be computed with this filter:
https://vtk.org/doc/nightly/html/classvtkImageConnectivityFilter.html

But, like most ImageData filters, this operates on point data, not cell data, and so still isn't quite what you may be after. But, if you have a cell-based input, you could use `cells_to_points` first to make it compatible with the point-based filter, use the filter, then do `points_to_cells` to return a cell-based representation. I believe this would generate the expected result of connected faces.

**Comment by GuillaumeBroggi** [comment]
Thanks for your useful tips! See #6659 for PR that implements such a connectivity filter.

**Comment by GuillaumeBroggi** [comment]
Close as #6659 was merged.
