### ISSUE TITLE
Glyph scaling broken since DataSetAttributes

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#754]
When I started to tackle https://github.com/pyvista/pyvista-support/issues/157#issuecomment-631158591 I noticed that my example worked on 0.24.2 but broke in master. I've tracked down the issue to commit https://github.com/pyvista/pyvista/commit/43ddfab438b00d9682206c8551976852fc2518a8 . I haven't tried investigating yet how things broke, I wanted to report it first.

-----
Simple glyph scaling example to reproduce:
```py
import numpy as np
import pyvista as pv

# get dataset where to put glyphs and scalars
x,y,z = np.mgrid[:3, :3, :3]
scalars = np.linspace(0, 1, x.size)
mesh = pv.StructuredGrid(x, y, z)
mesh.point_arrays['scalars'] = scalars

# construct the glyphs on top of the mesh; scale by scalars
glyphs = mesh.glyph(geom=pv.Sphere())

# create Plotter and add our glyphs with some nontrivial lighting
plotter = pv.Plotter(window_size=(1000, 800))
plotter.add_mesh(glyphs, specular=1, specular_power=15, smooth_shading=True)

# plotter.show(screenshot='screen.png')
plotter.show()
```
On the last working commit, fa124c390a46147fa2bdbc91000509ae0974cb88, I get this
![27 spheres in a cubical grid, with gradually changing radii](https://user-images.githubusercontent.com/17914410/82944695-f48f4a00-9f9b-11ea-8df9-56e10c5dc677.png)

The same code on the next commit, 43ddfab438b00d9682206c8551976852fc2518a8, gives me this:

![27 spheres in a cubical grid, all with the same buggy scaling](https://user-images.githubusercontent.com/17914410/82944769-15579f80-9f9c-11ea-9054-9ec1da00936b.png)

As you can see, scaling information is gone. In my original problem I wasn't actually using scaling, only scalars defined in the same way (with `.point_arrays['scalars'])`), so I suspect the bug has to do with the scalars themselves. Then again the colours correctly reflect the scalars. I haven't had time to investigate further yet.

**Comment by akaszynski** [comment]
This works:
```python
glyphs = mesh.glyph(geom=pv.Sphere(radius=0.5), scale='scalars')
```

Seems that setting the scalars does not immediately set them to be active within VTK as `SetActiveScalars` is not called upon setting the array.

@JevinJ, would you mind fixing this to restore previous behavior?  I'm thinking that the best place to add this would be at the end of `DataSetAttributes.append`.

@banesullivan, since you originally implemented this behavior, do you think it makes sense to always set the active scalars based on the last scalars set?  I didn't think about this until now, and I guess it makes intuitive sense to always do this.

**Comment by adeak** [comment]
I did check `mesh.active_scalars` after plotting, and it returned the proper scalars. Does this imply that they became active somewhere between the glyph creation and plotting? Perhaps during plotting?

**Comment by JevinJ** [comment]
This is kinda weird. it seems setting active in DataSetAttributes.append works as intended, but not if set in the example script above. Which is why mesh.active_scalars doesn't set them active. Maybe there is something I'm missing.


This should be the end of DSA.append()

`        self.VTKObject.AddArray(vtk_arr)
        try:
            self.active_scalars = name
            self.active_vectors = name
        except TypeError:
            pass
        self.VTKObject.Modified()`

Without the change to DSA, this doesn't work.


`import numpy as np
import pyvista as pv

# get dataset where to put glyphs and scalars
x,y,z = np.mgrid[:3, :3, :3]
scalars = np.linspace(0, 1, x.size)
mesh = pv.StructuredGrid(x, y, z)
mesh.point_arrays['scalars'] = scalars
mesh.GetPointData().SetActiveScalars('scalars')
mesh.GetPointData().Modified()
mesh.Modified()

# construct the glyphs on top of the mesh; scale by scalars
glyphs = mesh.glyph(geom=pv.Sphere())

# create Plotter and add our glyphs with some nontrivial lighting
plotter = pv.Plotter(window_size=(1000, 800))
plotter.add_mesh(glyphs, specular=1, specular_power=15, smooth_shading=True)

# plotter.show(screenshot='screen.png')
plotter.show()`

**Comment by akaszynski** [comment]
That fixes it for me.  Is there a way we could differentiate between scalars and vectors so we only set one or the other?

**Comment by adeak** [comment]
Since you're already touching it: there's a superfluous "the" or "this" in the docstring of `append` :)

**Comment by JevinJ** [comment]
@akaszynski Could add a bool for each in append(), if there isn't a way to extract that information from the array. (Like a certain dtype or something). With _ScalarsDict and derivatives it was always only the scalars being made active.

**Comment by akaszynski** [comment]
> Could add a bool for each in append()

That would be best.  Would you like to make the PR?

> With _ScalarsDict and derivatives it was always only the scalars being made active. And would set them active if active was None, which also works as a fix here.

Agreed.  Additionally, we need to add in a quick test to ensure active scalars are being set within VTK.  That way if we refactor/change this in the future we're guaranteed to continue to have the same functionality.

**Comment by JevinJ** [comment]
Any idea why the second code second I commented doesn't work?

**Comment by akaszynski** [comment]
In the course of this script we actually copy or set the point_arrays three times: once when actually setting the data, once when creating the `glyphs`, and once in `add_mesh`.  It seems that unless we set the active scalars when the mesh is copied, we lose that the active scalars information.

Verify this by putting in a `breakpoint` right the end of `append` in DSA.

**Comment by JevinJ** [comment]
Ok that makes sense. I'll have a fix shortly.

**Comment by JevinJ** [comment]
@akaszynski Fix is up.
