### ISSUE TITLE
Disable active scalars is not working

### ISSUE THREAD

**Issue by rodrigomologni** [pyvista/pyvista#835]
According to the PyVista 0.25.3 documentation, the `set_active_scalars(None)` method should disable the active scalars of the grid, but this is not working.

```
import pyvista as pv
import numpy as np

dims = 46, 69, 15
num_cells = np.array(dims) - 1
num_cells = np.prod(num_cells)
grid = pv.UniformGrid(dims)
grid.cell_arrays['cell_ids'] = np.arange(num_cells)
grid.set_active_scalars(None)
grid.plot(show_edges=True)
```

![image](https://user-images.githubusercontent.com/1608652/87457346-961b3b00-c5de-11ea-8b6f-7502c6b37cd6.png)

**Comment by banesullivan** [comment]
There is *always* an active scalar array on the mesh if it has arrays. If you want to plot the mesh with a solid color, you'll need to use the `color` argument `grid.plot(show_edges=True, color='orange')`

**Comment by banesullivan** [comment]
`grid.set_active_scalars(None)` will actually set the active scalars to the first found array if the PyVsita mesh isn't aware of which scalars are supposed to be active already. But when you use it above, it quietly does nothing which is intentional behavior

**Comment by banesullivan** [comment]
Actually, I retract what I said. We can deactivate the scalars but calling `.plot` with no `color` or `scalars` argument assume you want to plot the scalar data by default if you have it which was a very much intentional design decision.

So effectively, `.plot()` without the `color` argument is just reactivating those scalars

**Comment by banesullivan** [comment]
I suppose we could adjust `add_mesh` to account for this use case and not automatically activate scalars, but this could have undesired effects for a lot of our users that aren't even aware of the concept of active scalars and just call `.plot()` all over the place expecting data to be color mapped.

A while back we (perhaps just I) decided to implement it this way to make the API as simple as possible for most users because not all meshes will have active scalars upon loading and a user typically just calls `.plot()` with no arguments expecting scalars to be shown

**Comment by rodrigomologni** [comment]
Hi @banesullivan! Particularly, I am a user who likes to have the control of the visualization. But I understand your concern for other users. Thank you very much for the clarifications. 😉

**Comment by banesullivan** [comment]
> I am a user who likes to have the control of the visualization.

I totally understand. I'm hoping that using the `color` argument when plotting instead of `set_active_scalars(None)` is good enough compromise for users like you.

After all, the goal of PyVista's plotting API is convenience and cleverly choosing what most people want (e.g. choosing to color by any scalar data by default if no arguments are passed).

From my perspective, it's the advanced users like you or myself that should have to deal with the burden of making sure the arguments to `.plot()`/`add_mesh` are what we want. The default behavior is intended for people unfamiliar with the library that just want to visualize their 3D data as quickly as possible. This convenience is what attracts new users to PyVista and has enabled us to grow/gain the support we need to keep moving forward
