### ISSUE TITLE
using pyvista with python -i crashes on exit

### ISSUE THREAD

**Issue by jlinBE** [pyvista/pyvista#861]
importing pyvista under python -i crashes on exit under windows.

1. cmd
2. python -i
3. import pyvista
4. exit by clicking the X button instead of via exit()
5. crash:
![Clipboard01](https://user-images.githubusercontent.com/51561503/89852974-75410800-dbd3-11ea-951d-1ef1d50dd961.png)

**Comment by banesullivan** [comment]
Hm. I'm not familiar with using the `-i` mode of Python but this works fine on my Mac. I'd presume this is a typical case of Windows being Windows. The proper way to end a Python session is with `exit()`, so I'd recommend doing that rather than hitting the X window button.

Also, how was Python launched? There are a plethora of ways you could have launched it (anaconda prompt, powershell, command prompt, etc?) There's just a ton of factors here and frankly I suspect this isn't *really* a pyvista issue but more of a Windows+Python setup issue (and maybe some weird permissions problem - the "access violation" notice makes me think your Python isn't pro[erly configured to use system libs like OpenGL).

**And as always, please add a `Report` when submitting a bug per our issue templates:**

```py
import pyvista as pv
print(pv.Report())
```

------

Also, does this work without the `-i` option?

**Comment by jlinBE** [comment]
I launched it from command prompt (cmd), like I described above.

The same happens if I launch Python via py.exe, and run the same import.

Here's the output of pv.Report():

--------------------------------------------------------------------------------
  Date: Tue Aug 11 14:21:41 2020 AUS Eastern Standard Time

                OS : Windows
            CPU(s) : 32
           Machine : AMD64
      Architecture : 64bit
       Environment : Python
NVIDIA Corporation : GPU Vendor
GeForce RTX 2080 Ti/PCIe/SSE2 : GPU Renderer
4.5.0 NVIDIA 451.22 : GPU Version

  Python 3.8.5 (tags/v3.8.5:580fbb0, Jul 20 2020, 15:57:54) [MSC v.1924 64 bit
  (AMD64)]

           pyvista : 0.25.3
               vtk : 9.0.1
             numpy : 1.19.1
           imageio : 2.9.0
           appdirs : 1.4.4
            scooby : 0.5.6
            meshio : 4.1.0
        matplotlib : 3.3.0
             scipy : 1.5.2
--------------------------------------------------------------------------------

It's a clean install of python 3.8.5, no anaconda:

C:\Windows\System32>pip list
Package         Version
--------------- -------
appdirs         1.4.4
cycler          0.10.0
imageio         2.9.0
joblib          0.16.0
kiwisolver      1.2.0
matplotlib      3.3.0
meshio          4.1.0
natsort         7.0.1
numpy           1.19.1
Pillow          7.2.0
pip             20.2.1
pyparsing       2.4.7
python-dateutil 2.8.1
pyvista         0.25.3
scikit-learn    0.23.2
scipy           1.5.2
scooby          0.5.6
setuptools      47.1.0
six             1.15.0
threadpoolctl   2.1.0
vtk             9.0.1

**Comment by banesullivan** [comment]
What about just importing vtk:

```py
import vtk
```

**Comment by jlinBE** [comment]
import vtk then exit using X works, no crash.

**Comment by banesullivan** [comment]
Hm. Welp, then it must be something on PyVista's side. I currently do not have the ability to debug this (all I have is Mac and Linux), so we'll have to wait until someone (@pyvista/developers?) with some patience and a Windows machine is willing to debug what is happening here.

**Comment by akaszynski** [comment]
Checking if this is still an issue with ``0.27.0``.  We've changed quite a bit with the plotter since last release, and this might have been solved.

**Comment by jlinBE** [comment]
No longer crashing on Python 3.8.6 and pyvista 0.27.1.
