### ISSUE TITLE
add_point_labels for PlotterITK?

### ISSUE THREAD

**Issue by darikg** [pyvista/pyvista#895]
pv.PlotterITK doesn't inherit from pv.BasePlotter, so there's a a bunch of convenience `add_` methods missing.

I tried manually reimplementing it, but `add_point_labels` was a lot more complicated than I expected.

**Comment by akaszynski** [comment]
Hello,
I don't think that's supported at the moment within `itkwidgets`, so you may want to post your question [there](https://github.com/InsightSoftwareConsortium/itkwidgets), or correct me if I'm wrong.

You're right about `pv.PlotterITK` not inheriting much from the `BasePlotter`, and most of that stems from the fact that the two plotters are remarkably different and many features are not yet supported within `itkwidgets`.  It's been a few months since we've updated this section of code, so maybe there's been some additional APIs added.  If it does indeed support this, we can add this in.

**Comment by darikg** [comment]
Thanks @akaszynski, I think you're right about it not being possible with `itkwidgets`. I opened InsightSoftwareConsortium/itkwidgets#386 -- if I could get that cleared up I'll try submitting a PR here 🤞
