### ISSUE TITLE
More user control for lights

### ISSUE THREAD

**Issue by KDarshan20** [pyvista/pyvista#974]
Is it possible to create a point source of light in PyVista? More specifically, I want a light source at the center of the sun's mesh, and meshes of other planets in the screen should be lit according to the sun, with the part away from the sun dark, and vice versa. I found this link, and this seems to be possible in vtk (though this particular example is in C++): https://lorensen.github.io/VTKExamples/site/Cxx/Lighting/Light/

**Comment by KDarshan20** [comment]
Great!
By the way, the image looks cool.

**Comment by tkoyama010** [comment]
I agree.

**Comment by adeak** [comment]
I had some fun with this to see how easy it would be with PyVista:
```py
import pyvista as pv
from pyvista.examples import download_nefertiti
import vtk

data = download_nefertiti()

plotter = pv.Plotter()
plotter.add_mesh(data, color='white', smooth_shading=True)
plotter.set_background('black')
plotter.renderer.RemoveAllLights()

light_positions = [(-2, 2, 0), (2, -2, 0)]
light_colors = [(1, 0, 0), (0, 0, 1)]

for light_pos, light_color in zip(light_positions, light_colors):
  light = vtk.vtkLight()
  light.SetLightTypeToSceneLight()
  light.SetPosition(light_pos)
  light.SetConeAngle(90)
  light.SetFocalPoint(0, 0, 0)
  #light.SetPositional(True)
  #light.SetDiffuseColor(1, 0, 0)
  #light.SetAmbientColor(0, 1, 0)
  #light.SetSpecularColor(0, 0, 1)
  light.SetColor(light_color)
  
  plotter.renderer.AddLight(light)

plotter.show(cpos=[(-600, -850, 200), (0, 0, 0), (0, 0, 1)], screenshot='nefertiti_lit.png')
```
![nefertiti_lit](https://user-images.githubusercontent.com/17914410/98924770-7e44bc80-24d5-11eb-8c36-20432f42a5ed.png)

I left a few options I saw linked in https://github.com/pyvista/pyvista/issues/974#issue-732360803: the colour settings (just to signal they're available) and `light.SetPositional(True)` because I don't understand its significance and whether it would be necessary in general.

**Comment by akaszynski** [comment]
@adeak, do you think you could start a PR/branch with a pyvista subclassed `Light`?  I'd like to pythonize the vtkLight class and then add examples for it.  It will be very similar to our `Renderer` class.  This will need a file called pyvista/plotting/lights.py

**Comment by akaszynski** [comment]
@banesullivan and me are super busy at the moment; I've only been able to invest a lot of effort lately due to it aligning with my day job.

I'd start and we'll review it.

**Comment by adeak** [comment]
Sure thing @akaszynski, I'll take a shot at it, thanks.

**Comment by adeak** [comment]
@akaszynski I'm done with most of the implementation, but while trying to integrate the `pv.Light` class into the rest of pyvista I've run into a fundamental design problem.

You mentioned subclassing `vtkLight`, and I know that's how usually things are wrapped in pyvista. However, this means that if a base method returns a `vtkLight` then I can't wrap that in a way that gives me connected to the original light, I can only make a copy (at least I couldn't figure out how). For instance, I'd use a `Renderer`'s wrapped `AddLight()` method to add a `pv.Light`, but then `GetLights()` would give me `vtkLight` objects, and I don't see a simple way to promote these to `pv.Light` without copying.

So I've been wondering whether composition rather than inheritance would be the way to go. That way we can wrap any `vtkLight`, and the pythonic properties and other functions can affect the underlying `vtkLight`. A user can choose to use the `Light` API, or, say, directly the bare vtk methods on the lights grabbed from a renderer, and the result would be the same.

**Comment by akaszynski** [comment]
> I don't see a simple way to promote these to `pv.Light` without copying.

You could always provide a shallow copy of wrapped classes, and/or wrap `GetLights()` with a more pythonic `get_lights` that returns the `pyvista.Light` objects.

**Comment by adeak** [comment]
Assuming I understand correctly, "provide a shallow copy of wrapped classes" would be pretty much the composition alternative.

I already have implemented such a `get_lights`, but if the returned `pyvista.Light` objects are subclasses rather than thin wrappers then I don't think we can manipulate existing lights in a scene returned by this method.

Is it alright if I open a PR with the (working) composition-based implementation, or should I start with my earlier (broken) inheritance-based approach to try and see how to fix it?

**Comment by adeak** [comment]
OK, actually I think I got confused. If I add `pyvista.Light` objects to a renderer I can also retrieve them as such. So as long as the user (and the library) only adds the sublass, things should work. I'll update my implementation accordingly.

**Comment by adeak** [comment]
@KDarshan20 when the PR is released (or if you install pyvista master) you'll be able to do this:
```py
light = pv.Light(position=sun_coordinates)
light.positional = True
light.cone_angle = 90
plotter.add_light(light)
```
which will add a white spherical point source at `sun_coordinates`.
