### ISSUE TITLE
Set scalar bar ranges with slider widget

### ISSUE THREAD

**Issue by mcgoldba** [pyvista/pyvista#985]
I am attempting to set scalar bar limits interactively using a slider.  I have tried a solution that uses two slider bars (shown below).  However, I know of no way of extracting the value of the current scalar bar limits (e.g. `p.clim` is undefined), and the values are updated automatically whenever a scalar bar is changed.  As a result there seems to be no way of retaining both scalar bar limits, without the function resetting either the `max` or `min` value back to its original setting.

Here is would expect `p.clim` to return a tuple specifying the scalar bar limits, similar to the optional argument that can be specified within `Plotter.add_mesh(...,clim=[min, max],...)` (e.g. `[0,10]') 

```{py}
def set_scalar_bar_max(value):
    p.update_scalar_bar_range([p.clim[0],value])
    return
def set_scalar_bar_min(value):
    p.update_scalar_bar_range([value,p.clim[1]])
    return
p.add_slider_widget(
        set_scalar_bar_max, 
        title="Scalar Bar Max",
        rng=p.clim
)
p.add_slider_widget(
        set_scalar_bar_min, 
        title="Scalar Bar Min",
        rng=p.clim,
        pointa=(0.4,0.8),
        pointb=(0.9, 0.8)
)
```
I see a couple possible enhancements to allow for this functionality:
* Add a `clim` property that would allow for access to the current scalar bar limits
* Allow for multiple values to be set with one slider widget
* Allow for a manual update after modification of the slider widget (e,g,. with a "update" `button_widget`)

**Comment by banesullivan** [comment]
> Add a clim property that would allow for access to the current scalar bar limits

Can't happen because there can be N-many scalar bars and I will 👎 any new, bloating properties on the plotter like this. We could add a `get_scalar_bar_range(name=None)` method though similar to `update_scalar_bar_range`

> Allow for multiple values to be set with one slider widget

This is unfortunately out of scope for PyVista as we are simply using the slider widgets from VTK. A new widget would have to be written upstream in VTK-proper or in a separate offshoot project that could be monkey patched into the Plotter by that 3rd party lib.

-----

Generally, I think this is the wrong way to go about the goal. If you want an interactive UI, you should create one using PyQt or ipywidgets and have the slide *outside of the render window*. PyVista is a 3D mesh analysis, filtering, and plotting lib and we have to draw a line in the sand when it comes to adding new features for UI stuff. The widgets are a set of minimally working features meant for prototyping and rapid data exploration that I don't intend on expanding too much. ...with all that said.... I think this sort of feature request would be better suited for [`pyvistaqt`](https://github.com/pyvista/pyvistaqt) though again this seems more like something that would be done on the user-side in a custom app with PyVsita embedded rather than in PyVista itself.

**Comment by banesullivan** [comment]
With the upcoming #983 doing a slider with ipywidgets would be an excellent demo. @mcgoldba, it's on my agenda to get #983 merged and I will create a demo of doing just this in a Jupyter notebook for you then

**Comment by banesullivan** [comment]
#983 is landing soon and here is an example of a range slider to update the color bar limits:

```py
import pyvista as pv
from ipywidgets import widgets

mesh = pv.Wavelet().contour(5)

p = pv.Plotter()
p.add_mesh(mesh, stitle="My Colorbar")
p.add_axes()
view = p.show(use_ipyvtk=True, return_viewer=True)

slider = widgets.FloatRangeSlider(
    value=mesh.get_data_range(),
    min=0,
    max=500,
    step=1,
    description='clim:',
    continuous_update=False,
)

def on_slider_change(change):
    if change.type == 'change' and isinstance(change.new, tuple):
        p.update_scalar_bar_range(change.new, name='My Colorbar')
        view.update_canvas()

slider.observe(on_slider_change)

widgets.VBox([view, slider])
```

![2020-11-04 23 14 21](https://user-images.githubusercontent.com/22067021/98204574-89a35100-1ef3-11eb-85f6-b8cfa125f711.gif)

**Comment by mcgoldba** [comment]
Thanks!  I will test this out when available.
