### ISSUE TITLE
Should requirements_test.txt contain pytest-xdist?

### ISSUE THREAD

**Issue by adeak** [pyvista/pyvista#997]
When running `pytest` (version 6.1.2) on python 3.8 I get a warning:
```
../tmp_test_env/lib/python3.8/site-packages/_pytest/config/__init__.py:1230
  Unknown config option: looponfailroots

-- Docs: https://docs.pytest.org/en/stable/warnings.html
```

This refers to a line in `pytest.ini` that was added in https://github.com/pyvista/pyvista/commit/a8a37db8c as part of https://github.com/pyvista/pyvista/pull/745, but I can't see a specific mention of this exact change, so I don't know what it's for.

The `looponfailroots`, on the other hand, seems to be an undocumented feature in `pytest-xdist`, see https://github.com/pytest-dev/pytest-xdist/search?q=looponfailroots and https://github.com/pytest-dev/pytest-xdist/issues/499.

After installing `pytest-xdist` the warning goes away. Since warnings in tests aren't ideal, should we just add `pytest-xdist` to `requirements_test.txt`?

**Comment by akaszynski** [comment]
Funny you mention that.  I'm in the effort of cleaning up the tests and adding image regression in https://github.com/pyvista/pyvista/tree/testing/image_regression

As it turns out, the parallel testing strategy doesn't work, so I'm limiting it to single threaded testing and removing the ``pytest-xdist`` on Mac OS.
